### ISSUE TITLE
Facebookを利用したSNSログイン認証について。

### ISSUE THREAD

**Issue by Kyoheitnav** [NIFTYCloud-mbaas/UserCommunity#116]
はじめまして、AndroidSDKを用いた連携について質問があります。こちらのドキュメント(http://mb.cloud.nifty.com/doc/sdkguide/android/sns.html)を参考に、Facebookを用いたログイン認証を試そうとしたところ、ClassNotFoundException: com.facebook.Session$Builderで落ちてしまいました。
AndroidSDKを用いてFacebook認証をしたことの在る方どうかご教授お願いいたします。今のところ原因はFacebookSDKかNiftySDK内部かなと予想しています。

**Comment by Kyoheitnav** [comment]
解決できました！
FacebookSDKを１つ前のバージョンにしたところ上手く動きました！
Niftyさんの最新SDKが2015年の1月29日にリリースされており、
FacebookSDKの最新が2015年の2月5日にリリースされていました！
FacebookSDKの最新版にまだ対応していないのが原因かと思われます。
NiftyCloudSDK(Android)http://mb.cloud.nifty.com/doc/sdkdownload_android.html
FacebookSDK(Android)https://developers.facebook.com/docs/android/change-log-3.x?locale=ja_JP

**Comment by moongift** [comment]
@Kyoheitnav こちらフィードバックありがとうございます！開発に活かさせてもらいます！
