### ISSUE TITLE
datastoreでtransactionを実現する方法について

### ISSUE THREAD

**Issue by kyubuns** [NIFTYCloud-mbaas/UserCommunity#139]
datastoreで、複数の端末から同一レコードを操作する可能性がある実装を行いたいのですが、
どうにかしてtransactionを実現する方法はないでしょうか？

リファレンスにあるincrementが使えるんじゃないかと思ったのですが、実装を読むと、ローカルで値を足しているだけのように見えます。
http://mb.cloud.nifty.com/doc/sdkguide/unity/datastore.html

「レコードを読み込んできて、値に変更を加えて書き込もうとした時に、読み込んできた時とサーバーの値が違うとエラーになる」という挙動が実現できれば良いのですが、何か方法はありませんか？

**Comment by moongift** [comment]
@kyubuns 
仕様上、難しいと思いますが、例えば常にレコードを追加にして、最新の一件を使うようにするというのはどうでしょう？

**Comment by kyubuns** [comment]
ありがとうございます。その方向で方法を探ってみます。
