### ISSUE TITLE
mBaaSを検討しています

### ISSUE THREAD

**Issue by hiro25** [NIFTYCloud-mbaas/UserCommunity#157]
質問です。

現在、クライアントパソコンにインストールされたプログラムがWebサーバを監視しており、
Webサイト上(phpで開発されている)で、登録処理を行うと、
クライアントパソコンのプログラムがポップアップ画面を表示して、
登録処理が行われた旨のメッセージを表示する。ということを行っています。

この内容のものを、スマホアプリでも実装しようと考えた時に、
mBaaSサービスが検討対象に挙がったのですが、
上記のような内容のことは実現可能でしょうか？

処理フローとしては、Webサイト上で登録処理を行ったタイミングで、
Webサーバ上のphpのプログラムからプッシュ通知をする。
という感じになるのかと考えています。

以上、よろしくお願いいたします。

**Comment by moongift** [comment]
@hiro25 
そうですね。Webサーバ上でプッシュ通知を作成する流れになります。

PHP用のSDKは今のところありませんが、REST APIはありますのでプッシュ通知の作成はできるかと思います。

シグネチャを生成する処理は下記を参考にしていただければ。

http://qiita.com/niftycloud_mb/items/dee4558558e86175ccea

**Comment by hiro25** [comment]
早速のご回答ありがとうございます。

PHP用のSDKのご提供を切に願います。

スマホアプリの開発は初めて。
当然、ニフティクラウド mobile backendを利用するのも初めてですので、
またいろいろと質問させていただくと思いますが、よろしくお願いします。
