### ISSUE TITLE
認証期限が過ぎたID(メールアドレス)について

### ISSUE THREAD

**Issue by sakurabaryo** [NIFTYCloud-mbaas/UserCommunity#164]
メールアドレス/パスワード登録＋確認メールでユーザー登録を行っております。
認証期限(デフォルト24H)を過ぎてもユーザー登録が完了しなかった場合に、
そのメールアドレスでは二度と登録できなくなってしまいます。
NMBE内に「認証していな状態のメールアドレス」が残っているためです。

この様な状況を回避する方法はあるでしょうか？

**Comment by moongift** [comment]
@sakurabaryo 

今のところ、自動で削除する機能はありませんので、REST APIを使って定期的にそうした不要データを削除する形になるかと思います。

**Comment by sakurabaryo** [comment]
なるほど・・・・
有り難うございます。
