### ISSUE TITLE
プッシュ通知が未配信のまま

### ISSUE THREAD

**Issue by machimotako** [NIFTYCloud-mbaas/UserCommunity#172]
プッシュ通知の試験をしていて、プッシュ通知を繰り返し送信しています。
突然、新しいプッシュ通知を作成しても配信されなくなりました。

それまでは、問題なく配信されていました。
原因を調べるには、どうしたら良いでしょうか？

iOS向け配信
配信日時：今すぐ配信
![2015-05-27 19 41 22](https://cloud.githubusercontent.com/assets/4209676/7834297/d8c41500-04a8-11e5-953b-4d946548ef78.png)

**Comment by moongift** [comment]
@machimotako 
こちらプッシュ通知が殺到すると遅延する場合があるようです。現在もステータスは同じでしょうか？
なお、管理画面上からも遅延の原因を調べることはできません。なのでそうした時には[窓口に問い合わせる](http://mb.cloud.nifty.com/support.htm)のが良さそうです。

**Comment by machimotako** [comment]
質問を投稿した後、しばらくしたら配信されました。
その後は、問題なく配信できているので一時的なもののようですね。

原因を調べるには、窓口に問い合わせるしかないんですね。
ありがとうございました。
