### ISSUE TITLE
NCMB + Unity 4.6 とプラグインのコールバックとの併用について

### ISSUE THREAD

**Issue by asidemuraoka** [NIFTYCloud-mbaas/UserCommunity#197]
お世話になっております。

Unity 上で NCMB を利用して Android 用アプリケーションを作成しています。
システムで提供されているカメラロール（ギャラリー、自分で撮影した写真の一覧）を利用して、
写真を選択して、その写真を加工できるようにと考えていますが、うまくいきません。

カメラロールの写真選択は Unity からは直接行えないような感じなので（できるのであればその方がいいのですが…）、プラグインを作成して、以下のようなコードから写真選択画面を表示させようとしています。

>Intent intent = new Intent();
>intent.setType("image/*");
>intent.setAction(Intent.ACTION_OPEN_DOCUMENT);
>intent.addCategory(Intent.CATEGORY_OPENABLE);
>UnityPlayer.currentActivity.startActivityForResult( intent, 1 );

この方法であれば、カメラロールの表示ができるのですが、写真を選択しても本来呼び出されるべき 

>@Override protected void onActivityResult(int requestCode, int resultCode, Intent data) {
>    // 処理
>}

のイベントがコールされません。

たまたま、間違ってマニフェストで

>＜activity android:name="com.myplugin.gallery" ＞
>      ＜intent-filter＞
>        ＜action android:name="android.intent.action.MAIN" /＞
>        ＜category android:name="android.intent.category.LAUNCHER" /＞
>      ＜/intent-filter＞
>    ＜meta-data android:name="unityplayer.UnityActivity" android:value="false" /＞
>＜/activity＞

のように、間違えて intent-filter を設置してしまいインストールしてしまったのですが、そこでできてしまったこの "com.myplugin.gallery" のアイコンからアプリを起動して実行させると、正しく動作します。おそらく、この起動の仕方の場合に meta-data 欄の android:name="unityplayer.UnityActivity" android:value="false" が有効になったため、正しく動作したように思われます。

このマニフェストの intent-filter を削除してインストール・動作させると、先のイベント（onActivityResult）がコールされません。

おそらく、Unity のアプリケーションの Activity が通常の Unity のものではなく、それを継承した「   com.nifty.cloud.mb.UnityPlayerProxyActivity であるため、android:name="unityplayer.UnityActivity" android:value="false" が有効になっていないためかなと考えています。

なんらかの方法で写真選択した時に、先のイベント（onActivityResult）が発生できるようにしたいのですが、そもそもそのようなことが可能でしょうか？　それとも、提供されている NCMB のソースコードを変更する必要がありますでしょうか？

なんらかのアドバイスをいただければ大変助かります。
よろしくお願いいたします。

**Comment by moongift** [comment]
@asidemuraoka 

独自プラグインとの組み合わせだとかなり難しいですね…。あくまでも参考レベルですが、Unity SDKに含まれるAndroid向けネイティブプラグインであるNCMB_Push.jarがUnityPlayerActivityとUnityPlayerNativeActivityを継承したActivityを含んでいますのでこの辺りと関係している可能性がありますといったところです。

https://github.com/NIFTYCloud-mbaas/ncmb_unity/tree/master/Android

**Comment by asidemuraoka** [comment]
本件、自己解決しました。結果的には、NCMB ではなく、Unity 側の仕様の可能性が高いため、
この件についてはクローズとさせていだければと思います。ありがとうございました。
