### ISSUE TITLE
フィールドにACL設定

### ISSUE THREAD

**Issue by takuhub** [NIFTYCloud-mbaas/UserCommunity#201]
レコード単位では無くフィールド単位でACL設定は可能ですか？
もし可能であれば、その方法が知りたいです。

**Comment by moongift** [comment]
現状はないですね。別なクラスを作って、そことリレーションするのが良いのかなと。

**Comment by takuhub** [comment]
やはり、別のクラスを用意する必要がありそうですね。
ありがとうございます。
