### ISSUE TITLE
mBaaSではどれくらいのクエリがさばけるのでしょうか

### ISSUE THREAD

**Issue by Unimakura** [NIFTYCloud-mbaas/UserCommunity#205]
mBaaSの利用を考えているのですが、1秒間にどれくらいのクエリを実行できるのでしょうか？
・データ追加
・データ取得
それぞれどれくらいなのか目安が知りたいです。

また、プランをグレードアップしたらAPIなどの上限のみならず、スペックもあがるのでしょうか？

**Comment by moongift** [comment]
@Unimakura 

中の仕様についてはコミュニティよりも問い合わせベースのが良いかと思います。メールでの問い合わせはないので、

[相談会 | ニフティクラウド mobile backend](http://mb.cloud.nifty.com/consulting.htm)

を使って問い合わせるようです。

**Comment by Unimakura** [comment]
@moongift 

ありがとうございます、やはり相談会になるのですね。
相談会に行くとなると交通費がかなりかかるので悩ましいですね、、、一度検討してみます。
