### ISSUE TITLE
0レコードのクラスをqueryで検索した際に、successとなるのは何故か

### ISSUE THREAD

**Issue by IsseiEL** [NIFTYCloud-mbaas/UserCommunity#206]
初歩的な質問で申し訳ありません。
環境：Monaca、JavaScript

var attendance = NCMB.Object.extend("attendance");
var query = new NCMB.Query(attendance);
            
query.equalTo("username", currentUser.get("userName"));
上記は簡単なクエリ検索で、attendanceクラスを、
前もってログインしたログイン時のusernameと一致するもので検索したいのです。
ちなみにattendanceクラスは現在０レコード、空の状態です。
（attendanceクラス作成済み、usernameフィールドは存在する）

この状態で、上記ロジックを動作させた時、
query.find({
  success: function(results) {
    //成功
    }
  },
  error: function(error) {
    // エラー
  }
});
query.findで何故か成功の方に流れてしまうのですが、
0レコードだと、検索0件で失敗の方に流れることを想定しています。
何故でしょうか・・・。

この場合のquery.equalTo("username", currentUser.get("userName"));
の戻り値と、何故successに流れるのかが知りたいです。

何卒よろしくお願い致します。

**Comment by Rebirthble** [comment]
REST APIの仕様としてオブジェクト検索時にデータが見つからなかった場合も
「検索した結果、0件だった」というレスポンスがエラーにならないのでSDKもsuccessが実行されます。

http://mb.cloud.nifty.com/doc/current/rest/common/error.html

上記のエラーコードのうち404系のエラーは、存在しない値を参照しようとした場合に返却されるものです。
(例：存在しないobjectIdを指定した時)

**Comment by IsseiEL** [comment]
ご解答ありがとうございます、countでsuccessとなったのにも、
納得がいきました！どこかで、0件で存在しないからerrorとなるはずという固定観念があったようです。
これで、理解してロジックを実装できそうです。
