### ISSUE TITLE
CocoaPodsを使わない場合について

### ISSUE THREAD

**Issue by ulzexus** [NIFTYCloud-mbaas/UserCommunity#209]
お世話になっております。
mobilebackendについて、クイックスタートを参考に導入させていただきました。
その中で、cocospodsを利用せず、zipを落とす方法を使ってプロジェクトに組み込んでみたのですが、
実行時にエラーが出て困っています。

エラーが起きている箇所はNCMBURLConnection::convertResponseの、
if([self.path isEqualToString:[NSString stringWithFormat:@"/%@/%@", kAPIVersion, @"batch"]]){
で、self.pathへのアクセス時にBAD_ACCESSでアプリが落ちてしまいます。

また、今回組み込んだというプロジェクトがCocos2d-x v3.6を利用して作成されているプロジェクトで、
過去のやりとりでも似たような問題に遭遇している記事があったので拝見させていただいたのですが、
現状これの解決策というのは無いのでしょうか？

https://github.com/NIFTYCloud-mbaas/UserCommunity/issues/80

今回の要件としてはごく単純な、サーバーにデータを保存すること、サーバーからアプリ側にデータを受信することです。
参考になる資料や方法などがありましたら是非教えていただきたいです。
よろしくお願いします。

**Comment by nowsprinting** [comment]
ご質問（主題）の、CocoaPodsを使わずにSDKのソースを取り込むこと自体は可能で、動作しています。

ただし、Cocos2d-xで生成したプロジェクトにiOS SDKを取り込むことは公式には未サポートであり、例示されているエラーが出てしまうようです。
#80 のコメントにあるように、古いSDKで提供されていた.frameworkを使用することで動作する（らしい）、というのが現状のようです。

**Comment by ulzexus** [comment]
返信有難うございます。
古いSDKの.frameworkを利用する方法も試してみましたが、データのやりとりに関して上手く行ったり行かなかったりと不安定な印象を受けたので、今回は諦めることにします。
サポート対象外ですし当然の結果と言えますが、少々残念ですね・・・。

別のプロジェクトではIOS単体の開発もあるので、そちらでお世話になることにします。
ありがとうございました。
