### ISSUE TITLE
オブジェクト（既存レコード）の更新

### ISSUE THREAD

**Issue by IsseiEL** [NIFTYCloud-mbaas/UserCommunity#210]
初学者です。よろしくお願い致します。

http://mb.cloud.nifty.com/doc/current/sdkguide/javascript/datastore.html#オブジェクトの作成・更新

上記ページにて、オブジェクトの作成と更新について書かれています。
オブジェクトの作成（レコード追加）については、

var GameScore = NCMB.Object.extend("GameScore");
var gameScore = new GameScore();

gameScore.set("score", 1337);
gameScore.set("playerName", "Sean Plott");
gameScore.set("cheatMode", false);
gameScore.set("skills", ["pwnage", "flying"]);

gameScore.save(null, {
  success: function(gameScore) {
    // 値を変更して更新
    gameScore.set("cheatMode", true);
    gameScore.set("score", 1338);
    gameScore.save();
  }
});

上記を利用することで簡単にできたのですが、
既存レコードを、更新したい場合（キー値指定）。
どのように行えばよいのでしょうか？
gameScore.save(null, {
のnullにキー値を指定したのですが、
新規追加となってしまいました。

ご助言よろしくお願い致します。

**Comment by moongift** [comment]
@IsseiEL 
更新したいデータをfindで探して、そのデータでsave()を実行します。

```
var GameScore = NCMB.Object.extend("GameScore");
var query = new NCMB.Query(GameScore);
query.get("xWMyZ4YEGZ", {
  success: function(gameScore) {
    // 更新する処理
    gameScore.save();
  }
});
```

**Comment by IsseiEL** [comment]
お早いご解答ありがとうございます。
解決致しました。

ログイン処理があるアプリを想定します。
アプリにログインした状態で、現在のログインユーザーのデータを取得するところまでは
できていましたが、オブジェクトIDをSETしてSAVEできていませんでした。

以下コードです。

//レコード更新
var attendanceClass = NCMB.Object.extend("attendance");
var attendanceClass = new attendanceClass();

attendanceClass.set("attendanceFlg", true);
attendanceClass.set("objectId", results[0].id);

attendanceClass.save( {
  success: function(attendanceClass) {
     attendanceClass.save();
    //メニュー画面に遷移
    myNavigator.pushPage("menu.html"); 
  },
  error: function(attendanceClass, error) {
    //エラー時に実行される
    alert("Failed to create new object, with error code: " + error.message);
  }
});

※１results[0].idにfindしてきたオブジェクトIDが格納されています
※２attendanceFlgをtrueと更新して、メニュー画面に遷移します

無事更新することができました。お騒がせ致しました。
