### ISSUE TITLE
要望： ゆっくりPUSH通知を配信したい

### ISSUE THREAD

**Issue by yskfj** [NIFTYCloud-mbaas/UserCommunity#212]
現在5万件ほどPUSH通知の配信を行っていますが、およそ2分から3分の間でPUSH通知が端末に到着し
アプリからのリクエストでサーバの負荷が高くなってしまっています

例えば10分かけてゆっくり配信する等のオプションを選択できるように出来ないでしょうか

**Comment by moongift** [comment]
@yskfj 
ゆっくりというのはないので、対象をグルーピングした上で日時指定で配信するのが良いかと思います。instalationクラスの作成日時で分けても良いかと。

**Comment by yskfj** [comment]
配信を分割すれば良いのはわかっていますが、手間なのでそういう設定が有ったらいいなということで要望としていました
