### ISSUE TITLE
getInstallationIdでobjectIDが取得できない端末が発生する

### ISSUE THREAD

**Issue by sibhvn** [NIFTYCloud-mbaas/UserCommunity#220]
monacaを使用し、getInstallationIdでIDを取得しようとしています。
KYOSERA KYY23にてIDの取得ができず、ずっとnullでした。
以前は取得できていた気がするのですが、
突然取得できなくなるようなことってあるのでしょうか？

      var ncmbTimer = setInterval(function() {
        window.NCMB.monaca.getInstallationId(
          function(id) {
            console.log("ncmbTimer id = " + id);
            if (id) {
              clearInterval(ncmbTimer);
            }
          }
        );
      }, 5000);

**Comment by moongift** [comment]
@sibhvn 
こちらAndroidでしょうか？幾つか似たようなIssueがあがっているようです。
Monacaプラグインになるとデバッグが非常に困難なのですが、例えば以下のような方法が試せるかと。

- 登録先のmobile backendのアプリを新しいものにしてみる
- 端末のGoogleアカウント設定を確認してみる（Android 3系以前はGoogleアカウントの設定が必要だったかと思います） via https://developers.google.com/cloud-messaging/android/client
- Monacaの新しいアプリで試してみる

**Comment by sibhvn** [comment]
ご返答有難うございます。
端末日時を手動で変更していると取れなくなる模様です。
この当時他の部分の検証で日時を変更していたので、その影響なのかなと考えているところです。
