### ISSUE TITLE
iOS9 beta5 Xcode7 iOSSDK9 で NCMBInstallation:saveInBackground エラー

### ISSUE THREAD

**Issue by yskfj** [NIFTYCloud-mbaas/UserCommunity#222]
同じビルドバイナリでiOS8.4 iOS8.1 iOS7.1は正常にcurrentInstallationの保存ができています

pod 'NCMB', :git => 'https://github.com/NIFTYCloud-mbaas/ncmb_ios.git'
で最新版2.2.1が入っています

NCMBURLConnection.m の asyncConnectionWithBlock にログ出力を仕込んで実機で確認しました

sendAsynchronousRequest:queue:completionHandler: のcompletionHandlerでの connectionErrorはnilでした

送信データ: アプリ名とデバイストークンはxxxにしています
{"timeZone":"Asia\/Tokyo","deviceToken":"xxx","deviceType":"ios","appVersion":"2.12.291","applicationName":"ゴxxx","sdkVersion":"2.2.1","badge":0}

レスポンスデータ:
{"code":"E404001","error":"No data available."}

参考まで、Wiresharkで通信を確認しましたが、通信自体は問題ありませんでした

**Comment by yskfj** [comment]
mobile backendにログインして、該当デバイスのデバイストークンでinstallationクラスを検索してみましたが、居ませんでした。
登録自体ができていないようです。

**Comment by moongift** [comment]
@yskfj 
現時点のSDKではiOS 9に未対応となっています。今後検証し、対応予定とのことです。

**Comment by yskfj** [comment]
近々リリースされる（噂では来月）にもかかわらず、定形の返答でつれないですね。
iOS SDK ver2の時にもバグ取りやドキュメント修正にに協力したつもりですが残念です。
