### ISSUE TITLE
[ncmb-ruby-client] 複数オブジェクトが返ってくるところが同じオブジェクト

### ISSUE THREAD

**Issue by yugo-yamamoto** [NIFTYCloud-mbaas/UserCommunity#223]
ncmb-ruby-client のreadmeにあるサンプル（とほぼ同じデータストアの環境）を実行したのですが、複数オブジェクトが返ってくるはずが、同じオブジェクトがヒットした数だけ返ってきます。

readmeのサンプルの場合

```ruby
NCMB.initialize application_key: application_key,  client_key: client_key

@todo = NCMB::DataStore.new 'Todo'
@todo = @todo.limit(20).count(1).skip(0)
puts "@todo[0].name #{@todo[0].name}"
puts "@todo[1].name #{@todo[1].name}" #←追加
```
と最後に、次の行を取得しても、同じものがセットされているように見えます。

**Comment by moongift** [comment]
@yugo-yamamoto 
おっと、失礼しました。確認します。ncmb-ruby-clientは野良ライブラリになりますので

https://github.com/moongift/ncmb-ruby-client

にチケットを切っていただけますでしょうか？

**Comment by yugo-yamamoto** [comment]
失礼しました。こちらはクローズします。
