### ISSUE TITLE
414 Request-URI Too Large

### ISSUE THREAD

**Issue by Tak0002** [NIFTYCloud-mbaas/UserCommunity#237]
monacaとの組み合わせで開発しております。

```javascript
    query.containedIn("tuid",friends);
    query.descending("createDate");
    query.limit(10);
    query.skip(skip);
    query.find({
```

friendsの配列が大きすぎとこのようなエラーが出てしまうのですが、どう実装したらよいでしょうか？
分割して要求して、javascript側で結合するしかないのでしょうか？
アドバイスお願いします。
また、どのくらいで制限を超えるのか教えていただければと思います。

```
{"code":-1,"message":"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>414 Request-URI Too Large</title>\n</head><body>\n<h1>Request-URI Too Large</h1>\n<p>The requested URL's length exceeds the capacity\nlimit for this server.<br />\n</p>\n<hr>\n<address>Apache Server at admin.mb.api.cloud.nifty.com Port 80</address>\n</body></html>\n"}
```

**Comment by moongift** [comment]
やり方としては、

1. friendsの分割要求
2. friendsと、その元になるユーザをリレーションで結んでおいて、検索自体はユーザを指定しつつ、リレーションデータとしてfriendsを要求

という手があるのかなと。JavaScriptなので非同期実行が簡単なので、friendsの分割要求→結果を連結のが早い気もします。

URIの長さ設定は分かりませんが、デフォルトのApacheなどの場合8190byteのようですね。
