### ISSUE TITLE
料金プランについて

### ISSUE THREAD

**Issue by aimer1116** [NIFTYCloud-mbaas/UserCommunity#254]
http://mb.cloud.nifty.com/price.htm
新規登録時にプランの確認がなかったので、料金プランについて確認させてください。

* デフォルトは、無料プランになるのでしょうか？

* 無料プラン以外に切り替えは手動切替でしょうか？

* 無料プラン枠を超えた場合はどうなるでしょうか？

**Comment by ncmbsupport** [comment]
ご質問いただき、ありがとうございました。
以下のように回答いたします。

＋デフォルトは、無料プランになるのでしょうか？
　登録時のデフォルトは、Basicプラン（無料）が適用されます

＋無料プラン以外に切り替えは手動切替でしょうか？
　プランの変更は手動です。
　Expertプランへの変更はダッシュボード上で実施可能です。
　カスタマイズプランをご希望の場合は、サポート窓口へお問い合わせください。
　http://mb.cloud.nifty.com/support.htm

＋無料プラン枠を超えた場合はどうなるでしょうか？
　プランの上限を超えた場合、エラーを返却いたしますのでご注意ください。

プランの確認と変更の方法については以下のドキュメントをご参照ください。
　※http://mb.cloud.nifty.com/doc/current/dashboard/account.html

また、FAQにもよくある質問をまとめておりますのでご参考にしてください。
　※http://mb.cloud.nifty.com/faq.htm

**Comment by aimer1116** [comment]
ありがとうございます!
