### ISSUE TITLE
サーバー時間の取得方法について

### ISSUE THREAD

**Issue by SSK-ART** [NIFTYCloud-mbaas/UserCommunity#260]
サーバーの時間を取得する方法はありますでしょうか。

１日に３回だけ行えるというような処理を作りたいのですが、
端末時間だと変更されてしまうので、サーバーから時間の取得を行いたいと考えております。

**Comment by moongift** [comment]
一度適当なデータストアでデータを作成し、取得できたオブジェクトの中に時間があります。
updateDateか、createDateが使えるはずです。
