### ISSUE TITLE
javascriptのSDK(Version2)でのInstallationの更新方法

### ISSUE THREAD

**Issue by funfun12** [NIFTYCloud-mbaas/UserCommunity#266]
SDKを新しくして利用しているのですが、Installationクラスが無くどのように更新すれば良いのかわかりません。
http://mb.cloud.nifty.com/doc/current/sdkguide/javascript/datastore.html では標準クラスとして用意されている記載があるのですがまだ未実装なのでしょうか？
ncmb.DataStore("installation")をインスタンス化してupdate等を行うとURIが異なってしまうためエラーとなってしまいます。

**Comment by moongift** [comment]
@funfun12 

これ、不具合な気がします（または機能が足りないか）。フィードバックしておきます。

**Comment by moongift** [comment]
今の時点では対応していないそうです…。おそらく次以降のバージョンアップで対応するかと。

**Comment by funfun12** [comment]
回答ありがとうございました。
とりあえずは直接REST APIを利用して対応します。

**Comment by moongift** [comment]
2.0.1で対応した模様です！

https://github.com/NIFTYCloud-mbaas/ncmb_js/releases/tag/2.0.1
