### ISSUE TITLE
他ユーザーがログイン中かどうかを調べる方法

### ISSUE THREAD

**Issue by SSK-ART** [NIFTYCloud-mbaas/UserCommunity#273]
マッチングシステムのようなものを製作しているのですが、
他ユーザーが現在ログイン中かログアウト中かを調べる方法はないでしょうか。

**Comment by moongift** [comment]
ログインした時に、Onlineクラス的なものにログを残す形にしてはどうでしょう？ユーザ名と時間だけあれば良いかと思います。

**Comment by SSK-ART** [comment]
返答ありがとうございます。
ログインした際にログを残すところまでは問題ないのですが、ログアウト時の処理方法はどのようにすれば良いでしょうか。
アプリのタスクを切ってしまった場合に、ログを消す良い方法はありますでしょうか。

**Comment by moongift** [comment]
ログアウト自体はログアウト処理時にコールバックが受け取れますので、それで処理ができるかと。タスクを切った場合は難しいですね…データの更新日時を見て、10分以前ならログインしていないとみなす、とかでしょうか。
