### ISSUE TITLE
Unity&iOS&Androidでアプリ内から通知オン・オフは可能？

### ISSUE THREAD

**Issue by machiryo** [NIFTYCloud-mbaas/UserCommunity#297]
現在アプリ内から通知のオン・オフを実装しようとしているのですが、そもそもそのような機能はございます？

**Comment by moongift** [comment]
アプリから通知設定を変更することはできません。なのでInstallationクラスにreceivable的なカラムを作って、そこがtrueなら配信するといった条件を設けるのが良いかと思います。後はそのフラグをアプリから操作できる画面を作ってあげるイメージです。

ただ、Unity SDKの場合はInstallationのidが分からないので、Unityアプリからだと難しいかも知れません。

**Comment by machiryo** [comment]
ご回答ありがとうございます。

なるほどですね…

Unityアプリですので単純に端末の設定から通知許可・拒否する感じになりそうです。

またネイティブクラスからのアプローチが出来ないか調べてみます。
