### ISSUE TITLE
Facebook SDKのインストール後、linker command failed が発生してしまう

### ISSUE THREAD

**Issue by nashirox** [NIFTYCloud-mbaas/UserCommunity#299]
## 概要

[公式ドキュメント](http://mb.cloud.nifty.com/doc/current/sdkguide/ios/sns.html#Facebook SDKのインストール)に従ってFacebook SDKをインストールしたところ、表題のエラーが発生してしまいました。
### エラーログ

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FBSDKAccessToken", referenced from:
      objc-class-ref in NCMBFacebookUtils.o
  "_OBJC_CLASS_$_FBSDKLoginManager", referenced from:
      objc-class-ref in NCMBFacebookUtils.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
## やってみたこと
- 空の新規プロジェクトを作成し、NCMBだけ`pod install`
  - ビルド成功
- 次にFBSDKCoreKitを追加し、`pod install`
  - ビルド成功
- 最後にFBSDKLoginKitを追加し、`pod install`
  - ビルド失敗。表題のエラーが発生
### Podfile

```
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'hoge' do
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'NCMB', :git => 'https://github.com/NIFTYCloud-mbaas/ncmb_ios.git'
end
```
### スクリーンショット

![image](https://dl.dropboxusercontent.com/u/2579620/images/ss_ncmb.png)
## 構成
- Swift 2.1
- Xcode 7.1.1
- Pod
  - NCMB 2.2.3
  - FBSDKCoreKit 4.8.0
  - FBSDKLoginKit 4.8.0

以上です。対応策をご教示いただけると大変助かります。

**Comment by moongift** [comment]
@nashirox Swiftでの実装の場合、Podfileの use_frameworks! をコメントアウトしないといけないかと。一応、ドキュメントの

```
pod 'FBSDKCoreKit', '~> 4.1.0'
```

でも

```
pod 'FBSDKCoreKit'
```

でもビルドはできました。SDKに触ったところでエラーが出るかは未確認です。

**Comment by masuhara** [comment]
同じ事象で困っています。FBSDKのバージョンは下げたくないので対応してFBSDK 4.8.0に頂けると嬉しいのですが...

**Comment by gucchi43** [comment]
自分も同じ現象で困ってます。

swiftのもので、carthageが使えるものはそれで入れてるんですけど、対応してないものはPodfileに入れないとなので、どうしてもuse_frameworks書かないといけなくなってしまいます…

**Comment by naokits** [comment]
NCMB 2.3.0では次のようなエラーが発生したことをお伝えします。

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_NCMBFacebookUtils", referenced from:
      type metadata accessor for __ObjC.NCMBFacebookUtils in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

なお、上記のエラーは次の環境で確認しています。

- Xcode Version 7.3 (7D175)
- Podfileのuse_frameworks!オプションはオン
- CocoaPodsのバージョンは、1.0.0.beta.6

**Comment by sotozaki** [comment]
一時的な回避策になりそうです。
http://qiita.com/natsumo/items/74453049d58d67363c29

**Comment by SatoTakeshiX** [comment]
>一時的な回避策になりそうです。
>http://qiita.com/natsumo/items/74453049d58d67363c29
こちらで私の環境で成功しました！ビルドができました。
