### ISSUE TITLE
Unityでの匿名会員

### ISSUE THREAD

**Issue by actone-iwase** [NIFTYCloud-mbaas/UserCommunity#300]
Unityの機能ガイドに匿名会員の項目がありますが、利用方法についてのドキュメントが見つかりませんでした。
どのように利用したらよいのでしょうか？

**Comment by moongift** [comment]
@actone-iwase 

https://github.com/NIFTYCloud-mbaas/ncmb_unity/blob/master/NCMB/NCMBUser.cs

コードを見る限り、会員登録/ログイン機能は実装されていますが、匿名会員に関するコードは見当たりません。未実装かも知れません。

**Comment by actone-iwase** [comment]
ありがとうございます。
今回は利用を見送ろうと思います。
