### ISSUE TITLE
iOS『メールアドレス会員登録』機能でリジェクトされる

### ISSUE THREAD

**Issue by ZAKKAYA** [NIFTYCloud-mbaas/UserCommunity#364]
iOSでメールアドレス会員登録を行おうとすると、審査でリジェクトされてしまいます。

リジェクトの理由は『会員登録は、全てがアプリ内で完結しなければならない』とのことでした。

現在、メールアドレス認証の流れは

1.利用者がメールアドレスを入力して認証をリクエストする
2.入力したメールアドレスに対して会員登録画面へのURLを含むメールが送信される
3.メールから会員登録画面を開き、パスワードを入力して会員登録を行う
4.メールアドレスとパスワードでのログインが可能になる

となっておりますが、3.の”メールから会員登録画面を開く”際に、登録するアプリではなくサファリが
開き、サファリ内で登録することになる部分に問題があるようです。

そこで、URLスキームを使い、hoge://%link%　としても%linkしかURLと認識されずサファリしか開かないしで、どうしてもアプリに%link部分を飛ばせません。

現在リリースしているもののアップデートを考えているのですが、アップデートの変更点以外の、今までは審査が通っていた部分でこうなってしまうととても困っております。

どなたか良い方法をご存知ではありませんか？

ご教授願います。

**Comment by moongift** [comment]
#313 と同じかと思われます…。中の人でも解決策を模索しているようです。

**Comment by ZAKKAYA** [comment]
@moongift さん
確かにそうですね・・・すみませんでした。
私は解決したので#313 に記載しておきます。
ご意見ありがとうございました！

**Comment by cafedeichi** [comment]
@ZAKKAYA さん
参考までに"App Store Review Guidelines"に第何項に抵触したのか教えていただけますでしょうか。

以上につきまして、宜しくお願い致します。
