### ISSUE TITLE
Androidプッシュ通知でのトピックメッセージング対応について

### ISSUE THREAD

**Issue by heki1224** [NIFTYCloud-mbaas/UserCommunity#374]
サポートというよりも、機能面での問い合わせなのですが、
GCM 3.0 からサポートされた[トピックメッセージング](https://developers.google.com/cloud-messaging/topic-messaging)機能は対応しておりますでしょうか？
また今後対応する予定などありますでしょうか？

**Comment by moongift** [comment]
今のところ対応していないようです。今後のサービス改善として挙げたいとのことです。

**Comment by heki1224** [comment]
@moongift なるほど。情報ありがとうございます。
Parse.com が完全になくなるまでにプッシュ通知機能強化するとncmbに移行を検討してくれる会社増えそうですけどね。
