### ISSUE TITLE
メールアドレス認証における二重登録の防止方法

### ISSUE THREAD

**Issue by MK03** [NIFTYCloud-mbaas/UserCommunity#375]
お世話になっております。小林と申します。

表題の件ですが、メールアドレス認証によってアプリユーザーが会員登録するとき、すでに同じアドレスが登録されているか調べ、登録されているなら弾く仕掛けを組みたいと考えています。

NCMBQuery<NCMBObject> query = new NCMBQuery<>("user");

query.whereEqualTo("mailAddress", 入力されたメールアドレス);
int result = query.count();

としても、すでにメールアドレスが登録されているのにresultが0になってしまいます。

どうすれば、二重登録の防止ができますか。

お忙しい中恐縮ですが、よろしくお願い申し上げます。

**Comment by MK03** [comment]
なお、開発はandroid向けで行っております。

**Comment by moongift** [comment]
Public Readアクセスをつけてください。デフォルトではデータへのアクセス権限がありません。

**Comment by MK03** [comment]
ありがとうございます。解決しました。

**Comment by NT1974** [comment]
便乗で追加質問させて下さい。
・requestSignUpEmail() と同時もしくは直後に、同アドレスでの別ID登録を禁止したいと思います。
・しかし、ユーザーが作成される時点での ACL は自分自身にのみアクセス許可となっています。
　ACLを変更するには当該ユーザーがメール認証を終えてログインした時に変更するしかありません？
・そうだとすると、メール認証を終えてからログインするまでの間に、
　同メールアドレスで別の ID を登録する事が出来てしまいます。
・これを防ぐ手段は無いでしょうか？
