### ISSUE TITLE
スクリプト機能から外部ホストにリクエストが飛ばない

### ISSUE THREAD

**Issue by awwa** [NIFTYCloud-mbaas/UserCommunity#384]
先日追加され[たスクリプト機能](http://mb.cloud.nifty.com/doc/current/script/basic_usage_android.html)でsuperaganetを使って外部ホストにリクエストを飛ばそうとしているのですが、リクエストが飛ばない状況です。なにか思い当たるようなことがあれば教えていただけると幸いです。

アップロードしたスクリプト：
``` node
module.exports = function(req, res) {
  var request = require('superagent');
  request
   .post('http://requestb.in/XXXXXXX')
   .send('hoge=fuga')
   .end(function(err, res){
      console.log(res.body);
    });
  res.send("done");
}
```

今回はデバッグ用に[RequestBin](http://requestb.in/)で生成したランダムなURL（上記コードの「XXXXXXX」部分）をリクエスト先としており、mobile backendのコンソール上から実行してみました。
メソッド：POST
ファイルの状態：実行可能
バージョン：latest
パーミッション：全員

実行結果に"done"と出ているので、スクリプト自体は最後まで実行されているようです。
superagentの使い方は[公式サイト](https://visionmedia.github.io/superagent/#post-/-put-requests)を参考にしており、手元のNode.js環境で上記コードを実行したところリクエストが飛ぶことは確認しています。

**Comment by moongift** [comment]
doneと出るのは非同期処理だからですね。その時点で処理が終わってしまっているのかなと。

```
module.exports = function(req, res) {
  var request = require('superagent');
  request
   .post('http://requestb.in/XXXXXXX')
   .send('hoge=fuga')
   .end(function(err, res){
      console.log(res.body);
      res.send("done");
    });

}
```

だといかがでしょう？

**Comment by Rebirthble** [comment]
通信は行われているけれども、bodyプロパティが使えない状態かもしれません。
jsonデータなどを自動でparseできた場合に使えるプロパティなので、
res.textプロパティをいったん確認してみると結果が見られるかもしれません。

（参考）
http://visionmedia.github.io/superagent/#response-properties

**Comment by awwa** [comment]
@moongift @Rebirthble ありがとうございました。
基本的には @moongift さんの修正案をベースにして、以下のコードで期待する動作となりました。
``` node
module.exports = function(req, res) {
  var request = require('superagent');
  request
   .post('http://requestb.in/XXXXXXX')
   .send('hoge=fuga')
   .end(function(err, response){
     res.status(201)
       .json({result:"done"});
  });
}
```

、、、なるほど、ちょっと挙動を誤解していました。
コールバック内でresの関数を呼び出すことで処理を待ってから応答を返せるんですね。
逆に応答だけ先に返しちゃうと、その時点で終わっちゃうので、必要な処理の後でresの関数を呼び出せってことなんですかね。
長時間かかる処理を非同期実行したい時とかどうすればいいんだろう、という疑問は湧いてきますが、とりあえず、いまのところ解決できたのでまた必要な時に調べてみたいと思います。
