### ISSUE TITLE
エクスポートしたuser,role,pushクラスの別アプリへのインポート

### ISSUE THREAD

**Issue by dwomy** [NIFTYCloud-mbaas/UserCommunity#386]
ダッシュボードから全クラスのデータをエクスポート＞新規アプリを作成してインポートする際、
user,role,pushに関してはインポートは不可能なのでしょうか？
「会員登録」や「プッシュ通知」のメニューからはインポート項目は見当たらず、
データストア＞インポートからファイルをアップロードしてもエラーとなってしまいます。

**Comment by moongift** [comment]
デフォルトで用意されているクラスはインポートができないようです。

http://mb.cloud.nifty.com/doc/current/datastore/basic_usage_monaca.html#ファイルからクラスをインポートする

**Comment by dwomy** [comment]
なるほど…デフォルトで用意されているクラスに関しては、エクスポートした後で何かしらのインポート手段を用意するしかない感じですね。
ありがとうございます。
