### ISSUE TITLE
[記述間違い]Version2に伴う変更点ドキュメント

### ISSUE THREAD

**Issue by notoroid** [NIFTYCloud-mbaas/UserCommunity#457]
ドキュメント中の変更点のうち、

//プロパティ名
createdAt => createdDate

は、

//プロパティ名
createdAt => createDate

が正しいようです。

◾︎SDKガイド (iOS) : Version2に伴う変更点 | ニフティクラウド mobile backend
http://mb.cloud.nifty.com/doc/current/sdkguide/ios/versionChangeDescription.html

Googleで検索するとNCMBQuery、createdAt(以前のプロパティ名)で検索すると変更点ドキュメントしかヒットせず実際のプロパティがcreateDate であることを確認する際にちょいと手間が発生しております。

**Comment by moongift** [comment]
👍 
フィードバックします！

**Comment by moongift** [comment]
http://mb.cloud.nifty.com/doc/current/introduction/versionChangeDescription_ios.html
アップデートされました。

**Comment by notoroid** [comment]
👍
