### ISSUE TITLE
ユーザーのログアウト処理と削除を行う方法について

### ISSUE THREAD

**Issue by dwomy** [NIFTYCloud-mbaas/UserCommunity#465]
お世話になっております。

現在、javascriptにてログイン中の会員が退会に進んだ際に以下のような処理を記述しておりました。

```
// 1. ログインしていたユーザー(user)クラスの削除
user.delete();

// 2. セッションのクリアの為ログアウト
ncmb.User.logout();
```

ですが、上記では1と2の手順をどちらを先に行っても後に行ったほうが401となってしまいます。
（たまに成功することもありますが、挙動としては成功する方がおかしい？）

ログアウトとユーザー削除を同時に行う、もしくはリクエストを送らずにログアウトする事はできないのでしょうか？

**Comment by moongift** [comment]
ログアウト処理自体は `ncmb.User.logout();` なのですが、Web APIも叩いています。

https://github.com/NIFTYCloud-mbaas/ncmb_js/blob/master/lib/user.js#L779

で、すでにユーザがいないとこの処理が失敗しているのだと思います。かといって、ログアウト処理を行った後だと、user.deleteができない（権限がない）状態になるはずです。

処理的にはlocalStorageの

NCMB/APPLICATION_KEY/currentUser

を削除して、ncmb.sessionToken = null としてあげればログイン状態は解除されます。APPLICATION_KEYはNCMBで取得されるものです。

**Comment by dwomy** [comment]
迅速な回答ありがとうございます。
ご提案頂いた方法で試したいと思います。
