### ISSUE TITLE
データストアの検索

### ISSUE THREAD

**Issue by Tatsumi0000** [NIFTYCloud-mbaas/UserCommunity#477]
Androidでのデータストアの検索についてです。
ボタンを押すと、データストアを検索して、検索した文字がデータストアに存在する場合、「存在する。」、存在しない場合、「存在しない。」と表示するアプリを作っています。
しかし、データストアに検索した文字が存在する場合、存在しない場合両方共、「存在しない。」と表示されます。
以下のコートで実装しているのですが、どこに問題があるのでしょうか？
回答よろしくお願いします。

             Button btnDisp = (Button)findViewById(R.id.button);
             btnDisp.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                
                //TestClassを検索するためのNCMBQueryインスタンスを作成
                final NCMBQuery<NCMBObject> query = new NCMBQuery<>("TestClass");
                //TestFieldというフィールドがTestとなっているデータを検索する条件を設定
                query.whereEqualTo("TestField", "Test");
                //データストアからデータを検索
                query.findInBackground(new FindCallback<NCMBObject>() {
                    @Override
                    public void done(List<NCMBObject> results, NCMBException e) {
                        //検索失敗時の処理
                        if (e != null) {
                            
                            ((TextView)findViewById(R.id.textView2)).setText("検索失敗");
                            
                        } else {//検索成功時の処理
                            // 存在する場合
                            if (results.contains("Test")){
                                ((TextView)findViewById(R.id.textView)).setText("存在します。");
                                
                                //存在しない場合
                            } else {
                                ((TextView)findViewById(R.id.textView)).setText("存在しません。");
                            }
                        }
                    }
                });
            }
        });

**Comment by moongift** [comment]
containsはキーを指定ではなかったでしょうか？後、resultsは配列なので、resultsの1つ目に対して、TestFieldを探すのが良いのかなと。

**Comment by Tatsumi0000** [comment]
resultsの結果に対して、

if ("Test".equals(results.get(0).toString())){
((TextView)findViewById(R.id.textView)).setText("存在します。");
} else {
((TextView)findViewById(R.id.textView)).setText("存在しません。");
}

上記のようにif文を書いたところデータストアにあってもなくても存在しません。と出ました。


if文を消して、データストアにTestが存在するときにresultsの0番目を
((TextView)findViewById(R.id.textView)).setText(results.get(0).toString());
で表示したところ、
[com.nifty.cloud.mb.core.NCMBObject@45f6b1d]
が表示されました。

データストアにTestが存在しない時に表示すると
[]
が表示されました。
データストアに存在するときに表示すると、
Testが表示されると思ったのですが、どこが悪いのでしょうか。

**Comment by moongift** [comment]
```
results.get(0).getString("TestField")
```

ではないでしょうか？

http://mb.cloud.nifty.com/assets/sdk_doc/android/javadoc/index.html

**Comment by Tatsumi0000** [comment]
本当にありがとうございます！
getString()を使うのですね。
おかげさまで、問題が解決しました！！
