### ISSUE TITLE
Monacaからファイルストアを利用する方法

### ISSUE THREAD

**Issue by sazaleishi** [NIFTYCloud-mbaas/UserCommunity#482]
Monacaで画像ファイルアップロード機能を実装したいのですが、以下のサイトによると「現在ファイルストア機能をMonaca向けに提供していません」となっています。
http://mb.cloud.nifty.com/doc/current/filestore/basic_usage_monaca.html

しかし世の中のブログを読むと、Monacaからファイルストア機能を利用する実装例がたくさんあります（そのとおり実装してみましたが、うまく再現できませんでした）。
これは「従来は機能提供があったが、現在は機能提供がない」ということなのでしょうか、それとも私のコードのほうに原因があるだけなのでしょうか。

**Comment by aomiya11** [comment]
同じことでハマって、大変でした。。Qiitaにまとめましたので、よろしければ参考にしてください。
http://qiita.com/aomiya/items/c58b18ade560e7c1f91d
