### ISSUE TITLE
iOS でプッシュ通知が送れない

### ISSUE THREAD

**Issue by office-are** [NIFTYCloud-mbaas/UserCommunity#503]
お世話になります、cordova で作った iOS アプリにプッシュ通知を送れず困っています。何かアドバイスをいただけないでしょうか。 
----
cordova のアプリにプッシュ通知を実装しています。
Android には送れるのですが、iOS に送れません。
Android だけに送ると成功します。
Android + iOS に送ると失敗します。
iOS にだけ送ると失敗します。
iOS 端末は、送信予定の端末としてカウントされています。

送信予定の端末としてカウントされているの、証明書はうまく登録されていると思うのですが...

**Comment by moongift** [comment]
送信予定の端末はInstallationに該当するデータがあるかどうかなので、証明書の正しさとは別です。エラー内容によりますが、証明書が正しく登録されていない（秘密鍵も一緒にエクスポートされているなど）可能性があります。

**Comment by office-are** [comment]
回答、ありがとうございます。
一部解決しました。.p12 出力時にパスワードを設定したのが原因でした。「配信エラー」が「配信済み(一部エラー)」となり一歩進めました。
エラー内容は
    "ios": {
        "total": 1,
        "invalidToken": 1
    },
なので、Token まわりを調べてみます。

**Comment by office-are** [comment]
プッシュ通知の受信に成功しました。
以下のページの内容に従って証明書を作り直し、プロビジョニングをし直してうまくいきました

https://akira-watson.com/iphone/push-notification_1.html

**Comment by moongift** [comment]
👍
