### ISSUE TITLE
X-NCMB-Apps-Session-Tokenの取得方法について

### ISSUE THREAD

**Issue by onsoku** [NIFTYCloud-mbaas/UserCommunity#510]
データストアのinstallationへ登録済のレコードに対し、PUSH配信の検索条件として使用するフィールド追加しようと考えています。
バッチ処理にて「オブジェクト更新API」を使おうと考えているのですが
「**X-NCMB-Apps-Session-Token**」
の取得方法をご教授いただけないでしょうか。

ちなみにバッチ処理はPHPにて、下記を参考に作成しようと考えています。

> ニフティクラウド mobile backendの署名処理をPHPで実装してみた
> http://qiita.com/niftycloud_mb/items/dee4558558e86175ccea
>

**Comment by moongift** [comment]
X-NCMB-Apps-Session-Token はユーザ認証した際にサーバから返ってくるレスポンスヘッダーに含まれています。

**Comment by onsoku** [comment]
ご教授ありがとうございます。
色々と考えてみたのですが、PHPからのバッチ処理で、ユーザ認証を行うのはしんどそうでしたので
installationsAPIを使うように考えています。
正常系の処理のみですが、下記のソースコードにて、とりあえず動作しましたので共有します。
[ニフティクラウドのmobilebackendのinstallationの検索とフィールド追加をPHPでやってみた](http://qiita.com/onsokudiver/items/6f0a9b1a477a6fd23b18)

nodeJSが動く環境ならJavaScriptSDKを利用する方が断然オススメですね（涙；
