### ISSUE TITLE
where句をつけるとE403002エラー

### ISSUE THREAD

**Issue by silpheedkt** [NIFTYCloud-mbaas/UserCommunity#524]
https://github.com/NIFTYCloud-mbaas/UserCommunity/issues/506
が解決しないため、REST APIでの実装を試みています。
where句をつけると
{"code":"E403002","error":"Unauthorized operations for signature."}
となります。
類似の件を検索したところ、シグネチャ生成時に、
・URLエンコードは英文字は大文字で
・where=の=はURLエンコードしない
・キーの順番は、X-NCMB-*より、whereは後
・タイプスタンプはUTCで
・クエリ文字列以外はURLエンコードしない
ということは読み取れたのですが、いずれも満たしていますがエラーが解決しません。
where句をつけない全件取得は問題ありません。
シグネチャは、サンプルの値でテストしたところ一致するものが生成されるため、その処理自体には問題がないようです。
libcurl からのアクセスを試みています。
メソッドはGETのため、URLには ?where=(URLエンコードしたJSON)としています。検索キーは1つのみのためJSON内でのオーダーは関係ありません。

確認すべき内容がありましたら、アドバイスいただければ幸いです。

**Comment by moongift** [comment]
> URLエンコードは英文字は大文字で

これがちょっと不明です。後はシグネチャを生成しているコードを見れば多少アドバイスできるかも知れません。JavaScript SDKで同じ情報を与えてシグネチャを生成してみると分かりやすいかなと（日付のフォーマットが異なるので分かりづらいのですが）。

**Comment by silpheedkt** [comment]
ありがとうございます。
こちら側の実装に不備があり、文字列操作で意図しない結果が発生していたため、シグネチャの生成に不適切な値を入れてしまっていました。修正したところ、解決いたしました。
URLエンコードの件ですが、16進のA-Fは大文字にする、ということでした。
