### ISSUE TITLE
REST APIでiOSのプッシュ通知トークンを登録するとE400001エラー

### ISSUE THREAD

**Issue by silpheedkt** [NIFTYCloud-mbaas/UserCommunity#541]
iOSにてプッシュ通知用のトークンを取得し、SDKではなくREST APIでinstallationのdeviceTokenへ書き込もうとすると、

E400001
JSON is invalid format.

となります。
同様の処理をAndroidにて行うと問題なく完了する（ロジック部分は共通）ため、トークンの文字列が原因ではないかと思っているのですが、installationへ登録するトークンは、APNsのそれをそのままで問題ありませんでしょうか。
iOSのトークンは<>と空白文字列つきで渡ってくるためそれらを取り除いたりそのままで送ってみたりしましたが同様のエラーとなりました。

```
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    NSString *token = deviceToken.description;
    
    token = [token stringByReplacingOccurrencesOfString:@"<" withString:@""];
    token = [token stringByReplacingOccurrencesOfString:@">" withString:@""];
    token = [token stringByReplacingOccurrencesOfString:@" " withString:@""];
    
    NSLog(@"deviceToken: %@", token);

    Ncmb::registerToken([token UTF8String]);
}
```
といった感じで登録しようとしています（Ncmb::registerToken()はcocos2d-x側で実装したREST API呼び出しメソッドです）。

**Comment by moongift** [comment]
エラーを見るにJSONフォーマットの問題のようですが、実際のデータはどうなっているのでしょうか？

**Comment by silpheedkt** [comment]
ありがとうございます。
サンプルにあるJSON文字列をコピペしてもエラーが発生したため、調査したところ、libcurlにPOSTする値（JSON文字列）を渡した後にそのメモリが破壊されてしまっていました。
こちらを対策したところ、REST APIにてinstallationへ書き込みが成功するようになりました。
