### ISSUE TITLE
会員が自分で登録した画像のみ参照する方法について

### ISSUE THREAD

**Issue by ryutoyasugi** [NIFTYCloud-mbaas/UserCommunity#542]
Monacaで実装する際にどのようにするのがいいのでしょうか…

①ファイルストアに保存してバイナリを取得し、base64エンコードして表示
http://mb.cloud.nifty.com/doc/current/filestore/basic_usage_javascript.html#ファイルの中身を取得

②base64エンコードしてデータストアに保存

③できるのであればファイルストアでhttps公開してアクセス制御で自分のみ参照できるようにする

**Comment by moongift** [comment]
画像であればファイルストアですね。3は公開されていないといけないので、アクセス制限を考えるならば1になるかと思います。

**Comment by ryutoyasugi** [comment]
ご回答ありがとうございます

> 3は公開されていないといけないので
キャッシュが効くのでパフォーマンスを考慮してhttps公開にしようと思います。
セキュリティに関しては会員登録時の注意文言で対応を考えています。
