### ISSUE TITLE
ファイルストアにフォルダを保存する方法

### ISSUE THREAD

**Issue by leegun** [NIFTYCloud-mbaas/UserCommunity#564]
ファイルストアに静的なhtmlを保存してWebサイトのような使用を想定しております。
サイトにて表示するイメージリソースなどをimgフォルダなどにいれて、<img src = "img/hoge.png">のように使用したいのですが、フォルダをアップロードする事は出来ないのでしょうか？

初歩的質問かもしれませんが、よろしくお願い致します。

**Comment by moongift** [comment]
フォルダのアップロードはサポートされていません。

**Comment by leegun** [comment]
ご回答ありがとうございます。
他の方法を検討してみます。
