### ISSUE TITLE
【Swift】NCMBFileのurlが公開ファイルURLと異なる

### ISSUE THREAD

**Issue by Takayuki-Suzuki** [NIFTYCloud-mbaas/UserCommunity#569]
Swiftです。

コンソール画面のファイルストアに表示されている公開ファイルURLとfile.urlで取得できる文字列が異なります。
正しい動作でしょうか？

`
file.saveInBackgroundWithBlock({ (error: NSError!) -> Void in
  print(file.url)
})
`

**Comment by moongift** [comment]
urlは公開ファイルURLではないかなと思うのですが…どんな文字列が返ってくるでしょうか？

**Comment by Takayuki-Suzuki** [comment]
file.urlで取得できる文字列
https://mb.api.cloud.nifty.com/2013-09-01/files/{ファイル名}

公開ファイルURL
https://mb.api.cloud.nifty.com/2013-09-01/applications/{アプリID}/publicFiles/{ファイル名}

よろしくお願いいたします。

**Comment by moongift** [comment]
ですよね。 file.url は公開URLではなく、REST API用のURLになります。アプリIDは取れないはずなので。

http://mb.cloud.nifty.com/doc/current/rest/filestore/fileGet.html#ファイル取得APIについて

**Comment by Takayuki-Suzuki** [comment]
なるほど、勘違いでした。ありがとうございます。
