### ISSUE TITLE
プッシュ通知アプリを試したがinstallationにユーザーが追加されない

### ISSUE THREAD

**Issue by nomori7010** [NIFTYCloud-mbaas/UserCommunity#570]
下記サンプルアプリでiOSのプッシュ通知を試しました。
https://github.com/NIFTYCloud-mbaas/SwiftPushApp?_hsenc=p2ANqtz-9xIWn6isCMMjyfvXO5rcSeduTf18Cc5KYNpi-1gI6rK-tMGQJszjR_6k9QG3G2aV_9rXriO6UZH8v9uo82LhiI4-eeCA&_hsmi=32904303

マニュアル（readme.md）どおりに設定しましたがデータストアのinstallationにレコードが追加されません。
ビルドは通っていて、アプリ起動時に「”SwiftPushApp”は通知を送信します。よろしいですか？」というメッセージは表示され、[OK]で許可しています。
試しにXcodeでdidRegisterForRemoteNotificationsWithDeviceTokenメソッドの最初にブレークポイントをセットして実行しましたが呼び出されていない様子です。

どういった原因が考えられますでしょうか。
 #もしくはどのようにトラブルシューティングしていけばよろしいでしょうか。

**Comment by moongift** [comment]
これが参考になるでしょうか？

http://qiita.com/peromasamune/items/90970e9f9d5c34d21cfd

たぶん内容的には網羅しているはずなのですが…

**Comment by nomori7010** [comment]
ご回答ありがとうございます。
ただ、すでにそのように記述されているように見受けられます。
```
    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        
        // Override point for customization after application launch.
        //********** SDKの初期化 **********
        //NCMB.setApplicationKey(applicationkey, clientKey: clientkey)
        
        /// デバイストークンの要求
        if (NSFoundationVersionNumber > NSFoundationVersionNumber_iOS_7_1){
            /** iOS8以上 **/
             //通知のタイプを設定したsettingを用意
            let type : UIUserNotificationType = [.Alert, .Badge, .Sound]
            let setting = UIUserNotificationSettings(forTypes: type, categories: nil)
            //通知のタイプを設定
            application.registerUserNotificationSettings(setting)
            //DevoceTokenを要求
            application.registerForRemoteNotifications()
        }else{
            /** iOS8未満 **/
            let type : UIRemoteNotificationType = [.Alert, .Badge, .Sound]
            UIApplication.sharedApplication().registerForRemoteNotificationTypes(type)
        }

        FIRApp.configure()
        
        return true
    }
```

**Comment by moongift** [comment]
NCMB.setApplicationKey がコメントアウトされているのはたまたまですよね？

**Comment by nomori7010** [comment]
失礼しました。そうですね、たまたまです。
コメントアウトは外して動かしています。

**Comment by nomori7010** [comment]
何とか色々試してうまくいくようになりました。
証明書関連をいじっていたらできるようになった感じですが、どうして動くようになったかはわからないのでちょっと内容はかけません。
一度うまくいっていたのですが、また別問題が発生したので別のスレッドを立てます。
