### ISSUE TITLE
APIからプッシュ通知登録時にエラーコード[4]が返ってくるが、プッシュ通知は登録されている現象について

### ISSUE THREAD

**Issue by surfboard** [NIFTYCloud-mbaas/UserCommunity#599]
APIからプッシュ通知登録を行った際、毎回ではないのですが、

**エラーコード：4
エラーメッセージ：Respose parse error**

が返ってくる場合があります。
しかし、管理画面から確認するとプッシュ通知は正常に登録されていて、端末にプッシュ通知も正常に届きます。

レスポンス情報の解析に失敗したことによるエラーだと思うのですが、APIを送るこちらのプログラムが原因なのでしょうか？
もしくは一時的なNiftyさん側のエラーなのでしょうか？

ご教授いただければ幸いです。

**Comment by moongift** [comment]
レスポンスがパースできないということなので、レスポンスのメッセージに問題があるのだと思います。レスポンスをそのままログに残せればエラーの原因の切り分けができるかと思います。空文字なのか、レスポンスのJSONが途中で切れているとかでしょうか…。

**Comment by surfboard** [comment]
コメントありがとうございます。
なるほど、その方向で調査してみます。
また分からないことが出てきましたらよろしくお願いいたします。
