### ISSUE TITLE
会員情報の一部更新について…

### ISSUE THREAD

**Issue by YSE-YM** [NIFTYCloud-mbaas/UserCommunity#603]
以下のコードによって会員データの一部データの書き換えをしようとしたところ、
REST APIにてエラー発生（E404005,No such application.）となります。
どのように改良すればよろしいでしょうか？

var ncmb = new NCMB(appKey,clientKey);
Geo();

function Geo(){
    var currentUser = ncmb.User.getCurrentUser();
    if (currentUser) {
        console.log("ログイン中のユーザー: " + currentUser.get("userName"));
        console.log(lat);
        console.log(lng);
        currentUser.set("lat",lat)
        .set("lng",lng)
        .update()
        .then(function(){
            console.log("更新完了");
           // 更新後の処理
          })
         .catch(function(err){
           // エラー処理
            console.log("更新失敗");
            console.log(err);
         });
    } else {
        console.log("未ログインまたは取得に失敗");
    }

**Comment by moongift** [comment]
エラーメッセージから見るに、アプリケーションキーとクライアントキーの組み合わせに問題があるように見えます。または、

```
var currentUser = ncmb.User.getCurrentUser();
```

で使っているncmbオブジェクトに正しくアプリケーションキー、クライアントキーが入っていないのかも知れません。

**Comment by YSE-YM** [comment]
ご回答ありがとうございます。

![image](https://cloud.githubusercontent.com/assets/20217233/21334272/5ac184e4-c699-11e6-8226-0518b64373ff.png)

画像のようにconsole.log(currentUser.get("lat"));を記入したところ、
正しくデータが表示されていたため、データの受け渡しに問題があると考えました。
どのように変更すればよろしいでしょうか？

**Comment by YSE-YM** [comment]
ご回答ありがとうございます。
ncmbのデータの書き込み権限の変更を行ったことで解決しました。
このたびはありがとうございました。
