### ISSUE TITLE
パスワードリセットの条件について

### ISSUE THREAD

**Issue by tsogabe** [NIFTYCloud-mbaas/UserCommunity#604]
すみません，ちょっと見つからなかったもので，，
Unityでアプリの実験中です．
現在，
パスワード認証（やる）
メールアドレス認証（やらない）

の状態です．
全てのユーザのメールアドレスは登録してあります．
この状態でパスワードリセット機能をテストしたところ，リセットをかけたユーザだけ，何度リセットかけてもログインできなくなってしまいました．
Status codeは401です
【StatusCode】:401
【Error】:NCMB.NCMBException: Authentication error with ID/PASS incorrect.
【ResponseData】:{"code":"E401002","error":"Authentication error with ID/PASS incorrect."}

やはりメールアドレス認証が必要なのでしょうか？

**Comment by moongift** [comment]
パスワードリセットはリセット用のURLがメールアドレス宛に届くので、確かにメールアドレスが必須ですね…。

**Comment by tsogabe** [comment]
ご回答ありがとうございました．やはり認証されていないメールアドレスにリセットメールを送るのはおかしいですね．設定を変えてみたいと思います．
