### ISSUE TITLE
アプリからのPush通知送信で、送信元以外をターゲットにしたい

### ISSUE THREAD

**Issue by taragithub** [NIFTYCloud-mbaas/UserCommunity#621]
Monaca（JavaScript）を利用してアプリからPush通知する際に、その送信元以外（送信対象から送信元を除外）に通知したいのですが、searchConditionの記載方法が分かりません。
送信元にのみに送付するには、installationクラスのobjedtIdを比較する以下のようなコードになるかと思いますが、これと逆のことはできるでしょうか？

`var installationId;`
`window.NCMB.monaca.getInstallationId(function(id) {`
`installationId = id;`
`});`
`function pushNotice() {`
`var push = new ncmb.Push();`
`push.set("immediateDeliveryFlag", true)`
`.set("message","メッセージ")`
`.set("target", ["ios", "android"])`
`.set("searchCondition", {"objedtId":installationId});`
`push.send()`
`.then(function(push) {`
`//送信後処理`
`})`
`.catch(function(err){`
`console.log('pushNotice: ' + err);`
`});`
`},`

**Comment by moongift** [comment]
```
{
  "objectId": {
    "$ne": "aaa"
  }
}
```

こんな感じでいかがでしょう？

**Comment by taragithub** [comment]
moongift様
ご回答ありがとうございます。オペランドの記載方法を理解しました。ところで、上記の方法を自分の実機でテストしたい場合、良い方法はありますでしょうか？実機が一台しかありませんので、installationクラスに適当な架空のレコードを追加する、という方法になりますでしょうか？

**Comment by moongift** [comment]
そうですね。架空のデータを追加して、それを除外する形になると思います。

**Comment by taragithub** [comment]
moongift様
ありがとうございます。助かりました。
