### ISSUE TITLE
セーブした位置情報を上書きしたい

### ISSUE THREAD

**Issue by yoshiz3-onishi** [NIFTYCloud-mbaas/UserCommunity#625]
お世話になっております。

NCMBObject.saveInBackground() を使って複数人の位置情報を記録していますが、
同一人物の場合、位置情報を上書きしたいと思っています。
自動生成される objectId カラムを使って上書きなどできませんでしょうか？

NCMBQuery.findObjectsInBackground() こちらをつかって全データを取得し、
その中から目的のデータ NCMBObject を使って上書きはできそうではありますが、
データ数が数千、数万になってくると処理負荷問題が起こりそうなので
できれば避けたいと思います。

swift3 を使用。

**Comment by HiroHosono** [comment]
こんな感じで位置情報の上書きやってます。
個人ごとの設定ならばUserIDを付加しておいて、それをキーにオブジェクト取得して更新ができます。

func updateLocation(_ location:locationDef) -> Bool {
    
    let query = NCMBQuery(className: "Location")
    query?.whereKey("companyID", equalTo: location.companyID)
    query?.whereKey("locationID", equalTo: location.locationID)
    var results:[AnyObject] = []
    do {
        results = try query!.findObjects() as [AnyObject]
    } catch  let error1 as NSError  {
        print("\(error1)")
        return false
    }
    if results.count > 0 {
        let obj = results[0] as! NCMBObject
        
        obj.setObject(location.companyName,forKey:"CompanyName")
        obj.setObject(location.companyID,forKey:"companyID")
        obj.setObject(location.address, forKey: "Address")
        obj.setObject(location.LocationName, forKey: "LocationName")
        **obj.setObject(location.geo, forKey: "geo")**
        
        obj.saveInBackground({(error) in
            if error != nil {print("Save error : ",error!)}
        })
        return true
        
    }
    return false
}

**Comment by yoshiz3-onishi** [comment]
HiroHosonoさん

ご教示ありがとうございます！
教えていただいた方法で実現できました。
詳細なソースコードもありがとうございました。
