### ISSUE TITLE
NCMBUserを全て取得することはできますか？

### ISSUE THREAD

**Issue by SOTOCHA** [NIFTYCloud-mbaas/UserCommunity#638]
ユーザーを管理したい時に、ユーザ名一覧を管理者側のアプリから表示したいのですが、ドキュメントを探してもそれらしきメソッドが見当たりません。
まさかできないないのでしょうか…？

**Comment by DaichiSaito** [comment]
以下のコードでユーザ一覧を取得できると思います。
```
let query: NCMBQuery = NCMBQuery(className: "user")
query.findObjectsInBackground({(objects, error) in
    print(objects?.count)
})
```

なおその際、会員レコードのパーミッションを"全員"or"ロール"にする必要があると思われます。

<img width="502" alt="2017-02-21 16 44 06" src="https://cloud.githubusercontent.com/assets/10973259/23155533/542ca78c-f856-11e6-9019-cc49b9b655ce.png">

**Comment by SOTOCHA** [comment]
ありがとうございます。userと書いてあったんですね。
しかし、コードをコピペしても、取得できませんでした。
パーミッションも設定済みです。。。
<img width="699" alt="2017-02-21 18 36 16" src="https://cloud.githubusercontent.com/assets/1575019/23159041/b01607ba-f864-11e6-890f-5a3d95a18f48.png">

<img width="971" alt="2017-02-21 18 33 41 1" src="https://cloud.githubusercontent.com/assets/1575019/23159004/8ad7fe68-f864-11e6-9dfa-4cd6b8f763e9.png">

**Comment by DaichiSaito** [comment]
そうですか。。
ちなみに各会員レコードの"パーミッション編集"を押下した際、どのようなパーミッションが設定されていますか？私の方で試したところ、"対象"が"会員"になっていると、その会員しか当該レコードを取得できないようです。"対象"を"全員"にしてみたところ、取得できました。

![2017-02-21 19 06 17](https://cloud.githubusercontent.com/assets/10973259/23160278/31f8a09a-f869-11e6-8b96-998cd4449f7a.png)

**Comment by moongift** [comment]
クラスのパーミッションではなく、レコード単位のパーミッションになります。 @DaichiSaito さんの赤丸部分ですね。

**Comment by SOTOCHA** [comment]
御二方、ありがとうございます。
