### ISSUE TITLE
スクリプトで日付フィールドを登録すると、9時間ずれる

### ISSUE THREAD

**Issue by dokurocker** [NIFTYCloud-mbaas/UserCommunity#640]
```
var moment = require("moment");
moment.locale('ja');
ncmb.DataStore('test'))({
    'date': moment("2017/2/28", "YYYY/M/D").endOf('day').toDate()
}).save()
```
上記コードでtestクラスにレコードを追加し、ダッシュボードで追加されたレコードを見ると、dateフィールドが
```
2017-03-01T08:59:59.999+09:00
```
と想定より9時間進んで登録されてしまうのですが、
```
2017-02-28T23:59:59.999+09:00
```
とならないのはなぜですか？
（ドキュメント記載の開発環境では、23:59で登録されました）

**Comment by dokurocker** [comment]
開発環境のシステムのtimezoneをJSTにしていたため、開発環境では想定の値で登録されていたことがわかりました。
9時間の時差を考慮して登録するほかないでしょうか？

**Comment by moongift** [comment]
サーバ側の設定がUTCになっているのかと。アプリなのでグローバルに使われる以上、09:00を意識すると言うよりも、

```
2017-02-28T23:59:59.999+00:00
```

を意識する必要がありそうですね。

**Comment by dokurocker** [comment]
ご返信ありがとうございます。
>サーバ側の設定がUTC

確かにそのようです。

`2017/2/28`の部分がユーザーから日本の日付で入力されるため、
コード全体で日時をJSTとして扱いたいと思っていました。

普通のnodejsであれば、moment-timezoneを使用すれば可能そうですが、現状使えなかったので、素直に9時間減らしました。

```
var moment = require("moment");
moment.locale('ja');
ncmb.DataStore('test'))({
    'date': moment.utc("2017/2/28", "YYYY/M/D").endOf('day').subtract(9, 'h').toDate()
}).save()
```

**Comment by dokurocker** [comment]
解決いたしましたので、閉じます。
