### ISSUE TITLE
JavascriptでSyntaxError: Unexpected token !

### ISSUE THREAD

**Issue by HTsuruo** [NIFTYCloud-mbaas/UserCommunity#681]
javascriptを使って開発をしています。
導入で詰まってしまったのでなにか些細なことでもお教えいただきたいです。

importすると、Unexpected token ! とエラーが吐かれ動作しません。
```
var NCMB = require("ncmb");
```

探ってみるとmain.jsの194031行目にある以下の文で怒られている様子でした。
```
localStorage = new !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND';; throw e; }())("node-localstorage").LocalStorage("./scratch");
```

ちなみにパッケージはnpm経由でインストールしています。
```npm install -S ncmb```

以下私の環境です。
* nodejs: v6.9.2

大変困っております。
何か些細な事でもよろしいので情報のご提示をお願い致します。

**Comment by moongift** [comment]
再現できるコードがあるとアドバイスしやすいかなと。普通に試す限り、エラーは出ないので…。

**Comment by HTsuruo** [comment]
npm経由では上記のエラーは消えませんでしたが、ファイルをダウンロードして参照する形では動作しました。原因はnodeのバージョンの可能性が高かったす。
