### ISSUE TITLE
PlayCanvasでNCMBを使うためのソースコードと手順を公開しました

### ISSUE THREAD

**Issue by syyama** [NIFTYCloud-mbaas/UserCommunity#682]
掲題の通りですが、PlayCanvasでNCMBを使うためのソースコードと手順を公開しました！
宜しければ是非ご活用ください。

あと、活用して頂いた際はスターを押して頂けると幸いです。
https://github.com/syyama/ncmb-for-playcanvas

**Comment by moongift** [comment]
👍
