### ISSUE TITLE
1クラスに追加できるフィールド数の上限について

### ISSUE THREAD

**Issue by tossy-yossy** [NIFTYCloud-mbaas/UserCommunity#688]
1クラスに追加できるフィールド数の上限はありますでしょうか。
ドキュメント内に見つけることができませんでしたので、
ご存じの方がいらっしゃればお教えいただければと存じます。
よろしくお願いいたします。

**Comment by moongift** [comment]
mBaaSのバックエンドはMongoDBなので、その制限によるかと思います。

https://docs.mongodb.com/manual/reference/limits/#Size-of-Namespace-File

1ドキュメント16MBが基本の制限になるのかなと。ごく単純なデータを追加していくだけであれば、1,800カラムを越えても大丈夫でした。

**Comment by tossy-yossy** [comment]
moongift様
ご回答ありがとうございます。
検証までしていただき、深く感謝しております。
1,800カラムを超える要件は当方では存在しないため、気にせず利用できそうです。
