### ISSUE TITLE
cordova向けプラグインでサイレントPUSHを受信する方法

### ISSUE THREAD

**Issue by tossy-yossy** [NIFTYCloud-mbaas/UserCommunity#689]
cordova向けプラグインでサイレントPUSHを受信する方法はあるのでしょうか。
ドキュメントのURL等ございましたら、お教えいただけると幸いです。

**Comment by moongift** [comment]
受信はできると思いますが、その後JavaScriptのコードをキックする方法がないので使えないかと思います。Swiftなどのコードで実装するのであれば、

http://blog.mb.cloud.nifty.com/?p=8602

が参考になるかと（既存のプラグインを拡張する形になります）。

**Comment by tossy-yossy** [comment]
moongift様
返信ありがとうございます。
やはり既存プラグインを拡張するしか方法はなさそうですね。
いただいたURLを参考に、挑戦してみたいと思います。
