### ISSUE TITLE
メンテナンスモードについて

### ISSUE THREAD

**Issue by lofl** [NIFTYCloud-mbaas/UserCommunity#690]
アプリケーションのサービスを一時停止するためのメンテナンスモード（いわゆるソーシャルゲームなどのメンテナンス）をどのように実施すべきか検討しております。

APIを呼ぶ時に意図的にエラー情報を返すことができるのがよいのではと思いますが、意図してエラーにする方法はありますでしょうか。

今、思いついているのはメンテナンスモードにする時にアプリケーションキーかクライアントキーを変えてしまうというものですが、再生成しかできないようなので元に戻すのに一手間かかるように思います。全くNCMBにアクセスできなくなるのも問題あるかな？とも思いますが、皆様はどのように対処なされているのでしょうか？

**Comment by moongift** [comment]
システムのステータスを管理するクラスを追加して、アプリ起動時にそのステータスをチェックするのがいいかと思います。

**Comment by lofl** [comment]
ありがとうございます。

それだと、プレイ中にメンテナンス入りした時に、そのユーザーさんはプレイを続けられてしまうのでよろしくないような気がします...

**Comment by moongift** [comment]
メンテナンスは突然ある感じでしょうか？緊急メンテナンスの場合は難しいですね。

日程が決まっているのであれば、起動時にチェックして内部で保持しておくことで解決できるかなと。

**Comment by lofl** [comment]
そうですね。通常のメンテはスケジュールされているはずなので、その方法でいけそうですね。

緊急メンテがないとは絶対言えないと思いますが、そのときはそれこそキーを変えればいいのかなと。

ありがとうございました！
