### ISSUE TITLE
MonacaのFacecBookログインの実装方法が分かりません。

### ISSUE THREAD

**Issue by tsldeveloper** [NIFTYCloud-mbaas/UserCommunity#696]
Monacaとncmbを連携させて開発を行っている者です。

FBのアカウントを使ってNCMB側に会員登録/ログインを出来るように
したいのですが、アプリへの実装方法が分かりません。

ひとまず自分が調べた範囲内で、
①FB developerにてアプリを作成
②NCMB側にて、①で作成したAppIDを使ってしFacebook連携を許可

ここまでは終わりました。
しかし肝心の実装方法が分からなかったため、試しに下記ＵＲＬのソースを使って
http://mb.cloud.nifty.com/doc/current/sns/facebook_javascript.html#/JavaScript/
アプリに実装してみたのですが、

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
URLを読み込めません: このURLのドメインはアプリのドメインに含まれていません。
このURLを読み込むには、アプリ設定のアプリドメインにすべてのドメインと
サブドメインを追加してください。
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

というエラーが出てしまします。
「このURL」が何を指しているのかも分かりません。

どなたか、実装方法をご存知の方がいらっしゃいましたら
教えて頂けると幸いです。

**Comment by moongift** [comment]
Facebookアプリが許可するドメインとして設定が必要なのですが、そもそもアプリはドメインを持っていないためにエラーになります。そのため、Facebookが提供しているURL（https://www.facebook.com/connect/login_success.html）を指定する必要があります。

このURLをInAppBrowserで開いて、OAuth2トークンを取得すればうまくいくはずです。

http://blog.asial.co.jp/1432

こちらの実装が参考になるはずです。

**Comment by tsldeveloper** [comment]
ご回答いただきありがとうございます。
ご紹介して頂いたページの通りにやってみたらデータの取得が出来ました。

どこかで見かけたのですが、やはりFaceBook公式が出しているSDKだと
上手くいかないんでしょうかねぇ・・・ncmbのドキュメントに載っている方法だと
ずっとエラーになっていたので助かりました。

一点気になったのですが、Monacaデバッガーでは動作したのですが
クラウドＩＤＥのプレビューだとログイン/ログアウトの表示がなかったり
しているのは何故なんでしょうか？

**Comment by moongift** [comment]
Facebookの公式SDKはWebサーバでの利用を前提としているので、URLがないMonacaアプリでは動かないです。NCMBでも同様にHTTP以下での利用を想定しています。データが取れれば、後はそれをmBaaSに保存すれば良いだけです。

Monaca IDEでは外部ドメインへのアクセスに制限があるので、ネットワークアクセスの時点でエラーになってしまっているのだと思います。

**Comment by tsldeveloper** [comment]
再びご回答頂き有難うございます。

なるほど…そういう理由だったとは知りませんでした。
だからFBのログインボタンでもダメだったんですね。
あとはアクセストークンやIDを使って会員登録に挑戦してみようと思います。

大変丁寧な解説、ありがとうございました！

>>ドメインへのアクセスに制限があるので
configのアクセス許可とはまた別の制限があるんでしょうか？
とすると、実機 or Monacaデバッガーでしか確認できないみたいですね。

**Comment by moongift** [comment]
ドメインへのアクセス制限はCORS上の問題なので、Webブラウザでは解決できません。そうですね、これについてはMonacaデバッガーにてお願いします。
