### ISSUE TITLE
ObjectIDでデータを追加する時のエラー表示確認

### ISSUE THREAD

**Issue by hocnguyen** [NIFTYCloud-mbaas/UserCommunity#701]
以下の通りに、mbaasにテータを追加する為のREST APIを使用しました。 
{"objectId":"yQsxR7eeHMqOthhj","name":"test"}
しかし、{コード：「E403005」、エラー：「fieldName must not be entered.」}の返却結果が表示されていました。
送信したテータのobjectIdの値を削除したら、データ追加に成功しました。
なので、objectIdにより、データを追加する事が出来ないと認識していますが、
その認識は正しいのでしょうか？
ご確認の程、宜しくお願い致します。

**Comment by moongift** [comment]
objectIdはデータストアのユニークキーになりますのでデータ登録時には使えません。更新時にはこのobjectIdを使って更新対象を特定します。

データ登録と更新はHTTPメソッドが異なる（POSTとPUT）ので処理も分かれます。

↑こんな感じで大丈夫でしょうか？

**Comment by hocnguyen** [comment]
分かりました。ありがとうございます。
