### ISSUE TITLE
saveAllメソッドが利用できない。

### ISSUE THREAD

**Issue by DaichiSaito** [NIFTYCloud-mbaas/UserCommunity#702]
iOS
ver 2.3.4
です。

`NCMBObject`の`saveAll`メソッドを利用しリクエストを投げると以下エラーメッセージが返されます。

````
Error Domain=com.nifty.cloud.mb Code=404002 "None service." UserInfo={NSLocalizedDescription=None service.}
````

http://mb.cloud.nifty.com/doc/current/rest/common/error.html
によると、"該当サービスなし"とのことですが、`saveAll`メソッドは現在利用できないのでしょうか。
利用できないとなると、複数のオブジェクトを同時にmBaasに保存したい場合はどう実装すべきなのでしょうか。

**Comment by moongift** [comment]
batchというAPIは以前に廃止されました。恐らくSDK側の削除対応忘れと思われます。

実装としてはNSArrayを繰り返し処理して行う形になります。またはスクリプト機能を使う形になるかと。いずれにしてもトランザクションがサポートされる訳ではないのでご注意ください…。

**Comment by moongift** [comment]
良ければiOS SDKでIssue報告をお願いします！

https://github.com/NIFTYCloud-mbaas/ncmb_ios/issues/new

**Comment by DaichiSaito** [comment]
ありがとうございます。Issue報告しました。
実装方法についてもアドバイスありがとうございました。
