### ISSUE TITLE
データストアでユニークな値のフィールドを作成したい

### ISSUE THREAD

**Issue by tsldeveloper** [NIFTYCloud-mbaas/UserCommunity#706]
こんにちは、いつもお世話になっております。

NCMBのデータストアについてですが、重複を避けるために
ユニーク値を持つフィールドを作成したいと考えています。

ncmbのデータストアでは作成することが可能でしょうか？

**Comment by moongift** [comment]
インデックスの中でユニーク制約を有効にしてもらえれば良いかなと。

<img width="770" alt="screenshot_ 2017-04-28 17 02 25" src="https://cloud.githubusercontent.com/assets/5709/25519860/7c26a884-2c34-11e7-8e22-c8e0c8691b73.png">

**Comment by tsldeveloper** [comment]
教えて頂きありがとうございます！
しかしカスタマイズプランでないとできないみたいですね・・・うぅ

あと、差し出がましいようで申し訳ないのですが、
クラスから、オブジェクトIDを指定してレコードの削除を行うには、
どのメソッドを使用すればよろしいのでしょうか？
（ドキュメントにはダッシュボード上での削除方法しか載っていなかったので・・・）

教えて頂けると幸いです。

**Comment by moongift** [comment]
> カスタマイズプラン
あ…

データの削除はそのデータのobjectIdが分かっていれば、そのデータを指定して削除できます。例えばJavaScript SDKだと次のようになります。

```
var Item = ncmb.DataStore("Item");
var item = new Item;
item.set("objectId", "AAA"); // objectIdを指定
item.delete()
  .then((d) => {
    // 削除完了
  });
```

もちろんデータストアからfetchしてから削除も可能です。

**Comment by tsldeveloper** [comment]
再びご回答頂きありがとうございます！

なるほど、IDをセットしてdeleteメソッドで消すんですね。
ソースのサンプルまで頂きありがとうございます。

早速やってみたいとおもいます。
