### ISSUE TITLE
複数アプリで同じAPIkeyを使用して共通データを持つことは可能ですか？

### ISSUE THREAD

**Issue by souryu1217** [NIFTYCloud-mbaas/UserCommunity#712]
過去に同様の質問があり、特に返信のないままcloseされていたので再質問させていただきます。

アプリを跨いで共通のデータへアクセスするために、データベースにアクセスするためのAPIKeyについて
同じものを複数アプリに登録して実現しようと考えていますが、
アプリ設定が個別に設定出来ない以外で弊害、または使用できないのか、問題なく使用できるのかご教授頂けますと幸いです。

**Comment by moongift** [comment]
はい、できます。が、プッシュ通知はアプリIDに依存しますのでどちらかのアプリのみで使う（または常にアプリ名を条件に加える）などの工夫が必要です。

**Comment by souryu1217** [comment]
回答ありがとうございます。
本件は解決したためCloseさせて頂きます。
