### ISSUE TITLE
アプリアンインストール後のプッシュ通知について

### ISSUE THREAD

**Issue by tsldeveloper** [NIFTYCloud-mbaas/UserCommunity#716]
お世話になっております。

プッシュ通知は、データストアのinstallationクラスのデータを参照して
配信されると思うのですが、仮に対象アプリを端末からアンインストールした場合でも、
プッシュ通知はその端末に届くのでしょうか？

Installationクラスの登録されたデバイストークンを消さない限りは
配信され続けるのではないか？と思っているのですが、FCM側やAPN側で
アプリ削除時に何か処理が行われているのでしょうか？

**Comment by moongift** [comment]
アンインストールされた端末には届きません。そうしたデータはAPNsなどからエラーが上がってきますので、定期的に除去されます（数回は送るかも知れません）。自動で行われますので特に気にされずに大丈夫です。

**Comment by tsldeveloper** [comment]
ご回答頂き有難うございます。
そうなんですね、安心いたしました。
