### ISSUE TITLE
クライアントアプリから会員情報のパーミッションを書き込み許可する方法

### ISSUE THREAD

**Issue by ccyberx** [NIFTYCloud-mbaas/UserCommunity#743]
クライアントアプリから会員情報のパーミッションを書き込み許可する方法 

次の様なコードで良いでしょうか。

var ncmb = new NCMB(NCMB_apikey, NCMB_clientkey);
var acl = new ncmb.Acl();
acl.setUserWriteAccess({objectId:"ｘｘｘｘｘｘｘ"},true);

**Comment by moongift** [comment]
```
var ncmb = new NCMB(NCMB_apikey, NCMB_clientkey);
var acl = new ncmb.Acl();
acl.setUserWriteAccess("ｘｘｘｘｘｘｘ", true);
```

かなと。

**Comment by ccyberx** [comment]
ご回答ありがとうございました。
