### ISSUE TITLE
スクリプトからのデータ書き込み

### ISSUE THREAD

**Issue by o-uraya** [NIFTYCloud-mbaas/UserCommunity#763]
スクリプトからデータストアへ書き込みを行う.jsを書いたのですが、ローカルでは反映されるのですがスクリプトをサーバーへアップロードして実行するとデータストアへの書き込みが出来ないです。
パーミッション設定等ローカルとサーバーでの実行で違いはあるのでしょうか？
var Winning = ncmb.DataStore("Winning");
Winning.equalTo("ID", 1).fetch().then(function(results) {
	results.set( "UUID", winuuids );
	results.save();

    console.log(winuuids);
});

**Comment by goofmint** [comment]
JavaScriptはネットワーク処理が非同期なので、saveメソッドを実行しただけだと直後に終了してしまいます。saveメソッドの結果を待って処理を終了するようにしてください。

```
var Winning = ncmb.DataStore("Winning");
Winning.equalTo("ID", 1).fetch().then(function(results) {
results.set( "UUID", winuuids );
results
  .save()
  .then(function(data) {
    res.status(200).json({});
    console.log(winuuids);
});
```

**Comment by o-uraya** [comment]
ありがとうございます、書き込み出来ました。
ローカル実行だと書き込み出来るのは裏で最後まで動いてるからなのかしら・・・
