### ISSUE TITLE
パスワードリセットが失敗する

### ISSUE THREAD

**Issue by tanakahisakichi** [NIFTYCloud-mbaas/UserCommunity#778]
初心者エンジニアです。

サンプルアプリを用いて、ログインをした後に、
会員管理画面で入力したメールアドレスを参照して、
パスワードリセットを行おうとしていますがうまくいきません。

下記にコードを記します。

js

var ncmb = new NCMB(appKey, clientKey);

///// Called when app launch
$(function() {
  $("#LoginBtn").click(onLoginBtn);
  $("#RegisterBtn").click(onRegisterBtn);
  $("#YesBtn_logout").click(onLogoutBtn);
  $("#ResetBtn").click(onResetBtn);
});

//----------------------------------USER MANAGEMENT-------------------------------------//
var currentLoginUser; //現在ログイン中ユーザー

function onRegisterBtn()
{
    //入力フォームからusername, password変数にセット
    var username = $("#reg_username").val();
    var password = $("#reg_password").val();
    
    var user = new ncmb.User();
    user.set("userName", username)
        .set("password", password);
    
    // 任意フィールドに値を追加 
    user.signUpByAccount()
        .then(function(user) {
            alert("新規登録に成功");
            currentLoginUser = ncmb.User.getCurrentUser();
            $.mobile.changePage('#DetailPage');
        })
        .catch(function(error) {
            alert("新規登録に失敗！次のエラー発生：" + error);
        });
}

function onLoginBtn()
{
    var username = $("#login_username").val();
    var password = $("#login_password").val();
    // ユーザー名とパスワードでログイン
    ncmb.User.login(username, password)
        .then(function(user) {
            alert("ログイン成功");
            currentLoginUser = ncmb.User.getCurrentUser();
            $.mobile.changePage('#DetailPage');
        })
        .catch(function(error) {
            alert("ログイン失敗！次のエラー発生: " + error);
        });
}

function onLogoutBtn()
{
    ncmb.User.logout();
    alert('ログアウト成功');
    currentLoginUser = null;
    $.mobile.changePage('#LoginPage');
}
function onResetBtn()
{   
    currentLoginUser =ncmb.User.getCurrentUser ();
    //currentLoginUser.get("mailAddress");
    currentLoginUser.set("mailAddress");
    currentLoginUser.requestPasswordReset()
    .then(function(data){
      console.log("送信完了");
    })
    .catch(function(err){
      console.log("送信失敗");
    })
}

よろしくお願いいたします。

**Comment by goofmint** [comment]
どのようなエラーが出るのでしょうか？ちなみに `onResetBtn` のところの `ncmb.User.getCurrentUser ();` で、getCurrentUserの後ろにスペースが入っているが気になります。

**Comment by tanakahisakichi** [comment]
自己解決いたしました。

ご助力ありがとうございました。
