### ISSUE TITLE
【Unity】installationが更新されたタイミングでプッシュ通知を送信したい

### ISSUE THREAD

**Issue by waspossible** [NIFTYCloud-mbaas/UserCommunity#782]
いつも利用させて頂いております。

データストアにてゲームのハイスコアを記録しております。
scriptから、ハイスコア（全体1位）が塗り替えられた時に、いままで1位だった記録のユーザの端末情報をinstallationに記録し、その端末に向けて「ハイスコアを抜き返しましょう」的なプッシュ通知を送る事を考えております。
installationが更新されたタイミングで自動でプッシュ通知を送信する事は可能でしょうか。ダッシュボードからですとそのような項目が見つかりませんでした。
返答をよろしくお願いいたします。

**Comment by goofmint** [comment]
フローとしてはハイスコアを取ったユーザが、それまでハイスコアだったユーザに対してプッシュ通知を送る方が分かりやすいかと思います。

もしハイスコアをInstallationに残しているのだとしたら、ハイスコア未満のデータで一件目（つまり2位になったデータ）に対してプッシュ通知を送るという条件付けになります。

**Comment by waspossible** [comment]
お忙しい所回答頂きありがとうございます。難しく考え過ぎておりました。諦めずに粘り強くトライしてみます。また壁にぶつかりましたら、頼らせて下さい。
