### ISSUE TITLE
iOSプッシュ通知の証明書でパスワードが入る場合

### ISSUE THREAD

**Issue by Quangna** [NIFTYCloud-mbaas/UserCommunity#784]
iOSプッシュ通知の証明書（p12）でパスワードがある場合、アプリでプッシュへ届いてない。どうすればいいの？

**Comment by goofmint** [comment]
http://mb.cloud.nifty.com/doc/current/tutorial/push_setup_ios.html#証明書を.p12形式に変換する

> パスワードを設定すると、mobile backendにアップロードしても利用できなくなります。

とあります。
