### ISSUE TITLE
push通知(REST API経由)を、全体ではなく、複数の特定ユーザーに送りたい

### ISSUE THREAD

**Issue by kuniakisuzuki** [NIFTYCloud-mbaas/UserCommunity#789]
push通知のため、mobile backendの導入を検討しているのですが、表題のような事は出来ますでしょうか。

http://mb.cloud.nifty.com/doc/current/rest/push/pushRegistration.html
を見る限りでは、targetのところに、デバイスのtokenを含めていけば出来そうに思うのですが、
極端に言えば、そこに、千、1万などのtokenを登録して、問題なく送れるものなのでしょうか…？

**Comment by goofmint** [comment]
targetはiosまたはandroidを指定します。絞り込み条件はsearchConditionを使います。searchConditionで配列を使ってトークンを指定することはできますが、1万だとエラーになる気がします。何らかの条件（ユーザ登録日がいついつ以前、など）をsearchConditionで使うのであれば対象が1万でも10万でも問題ありません。

**Comment by kuniakisuzuki** [comment]
ご返信、ありがとうございます…！

searchConditionでtokenを指定できるのですね、その辺りのドキュメント記載など、どこか載っている場所ございましたでしょうか…？

http://mb.cloud.nifty.com/doc/current/rest/push/pushRegistration.html
を見る限りでは、searchConditionに何が入ることを想定されているかわからなかったので…

**Comment by goofmint** [comment]
ちょっと分かりづらいですが、↑のURLの下の方にあります。

**検索条件の例**

```
    "searchCondition": {
        "channels": "ch1",
        "appVersion": "1.0" 
    }
```

searchConditionはInstallationクラスを絞り込む条件を記述します。Installationクラスに独自のカラムを追加すれば、それも条件に指定できますし、以上以下といった条件でも指定できます。

**Comment by kuniakisuzuki** [comment]
早速のご返信、ありがとうございます！

なるほど、Installationクラスが対象になるのですね…！

>1万だとエラーになる気がします。

また、こちら、何件までがmaxか、などの情報はございますでしょうか…？
予め属性でグルーピング出来ていればいいのですが、今回、メール配信システムのように、「誰に事前に送るかわからないが、最大で数百〜数千になる」というようなpush配信の物を作りたいと思っておりまして…。

**Comment by goofmint** [comment]
恐らく公表されている資料はないかと思います。他社の事例では個別配信（Installationクラスをあらかじめ検索して、返ってきたデータ1件1件に対してプッシュ通知を作成）が多いようです。配列で指定は負荷が高いので、配信に時間がかかる可能性もあるかなと…。

**Comment by kuniakisuzuki** [comment]
情報、ありがとうございます、そうですよね、1件1件に分けていくという方法もありますよね…。

国内のサービスにはあまり無いようだったのですが、
http://docs.pushwoosh.com/docs/createmessage
など、海外まで広げてみると、一応、1000件未満であれば大丈夫、
と記載されているものもあるようなので、そういったものを検討してみようと思います。

様々なご助言をいただき、本当に助かりました、ありがとうございます…！
