### ISSUE TITLE
REST API呼び出しでサーバスクリプトを実行するには

### ISSUE THREAD

**Issue by nam1c** [NIFTYCloud-mbaas/UserCommunity#791]
REST APIを使ってNCMBサーバスクリプトを実行するにはどのようにすれば良いでしょうか。
以下の記事を参考にシグネチャを作成し、

ニフティクラウド mobile backendの署名処理をPHPで実装してみた
https://qiita.com/niftycloud_mb/items/dee4558558e86175ccea

cUrlから呼び出してみたのですが、
エラーE401001 Authentication error by header incorrect. 
となってしまいます。
シグネチャ生成の初歩的なミスかもしれませんが、ご教授いただければ幸いです。

NCMBサーバスクリプト"foo.js"
```node.js:NCMBサーバスクリプト"foo.js"
module.exports = function(req, res) {
  res.send("my name is " + req.query.name);
}
```

シグネチャ生成PHP
```PHP:シグネチャ生成PHP
<?php
$method = 'GET';
$fqdn   = 'script.mb.api.cloud.nifty.com';
$api_version = '2013-09-01';
$path        = 'script/foo.js';
$hash = [];
$hash['where'] = json_encode(array("name" => "fooo"));
$timestamp = date(DATE_ISO8601, time());

$application_key = 'アプリケーションキーを設定';
$client_key      = 'クライアントキーを設定';

$header_string  = "SignatureMethod=HmacSHA256&";
$header_string .= "SignatureVersion=2&";
$header_string .= "X-NCMB-Application-Key=".$application_key . "&";
$header_string .= "X-NCMB-Timestamp=".$timestamp . "&";
$header_string .= http_build_query($hash);

$signature_string  = $method . "\n";
$signature_string .= $fqdn . "\n";
$signature_string .= "/" . $api_version . "/" . $path ."\n";
$signature_string .= $header_string;

echo base64_encode(hash_hmac("sha256", $signature_string, $client_key, true)); 
echo "\n";
?>
```

テスト実行コマンド
```cUrl:テスト実行コマンド
curl -X GET -G \
-H "X-NCMB-Application-Key: アプリケーションキーを設定" \
-H "X-NCMB-Timestamp: 2017-10-01T07:09:28.637Z" \
-H "X-NCMB-Signature: c/bf6J5fLn6TwHSH2Mj6j9ef1Xsv3QO5GPohALDBjqg=" \
-H "Content-Type: application/json" \
 https://script.mb.api.cloud.nifty.com/2013-09-01/script/foo.js?name=fooo
```

**Comment by ncmbadmin** [comment]
コミュニティへのご投稿、ありがとうございます。
こちら、主な原因は以下3点となります。

1)$api_version

スクリプトREST APIのバージョンは「2015-09-01」となります。
参考:http://mb.cloud.nifty.com/doc/current/rest/script/scriptExecution.html#基本仕様

2)クエリ指定部分

・ timestampの後、「&name=foo」等の形式にてつなげて頂ければと思います。

3)テスト実行コマンド

$timestampをシグネチャ生成時の$timestampと一致させる必要がございます。

サンプルスクリプトは下記となりますので、ご参考ください。

▼NCMBサーバースクリプト"foo.js"
```
module.exports = function(req, res) {
  res.send("my name is " + req.query.name);
}
```

▼シグネチャ生成PHP
```
<?php
$method = 'GET';
$fqdn   = 'script.mb.api.cloud.nifty.com';
$api_version = '2015-09-01';
$path        = 'script/foo.js';
$query = 'name=foo';
$timestamp = date(DATE_ISO8601, time());

$application_key = 'アプリケーションキー';
$client_key      = 'クライアントキー';

$header_string  = "SignatureMethod=HmacSHA256&";
$header_string .= "SignatureVersion=2&";
$header_string .= "X-NCMB-Application-Key=".$application_key . "&";
$header_string .= "X-NCMB-Timestamp=" .$timestamp . "&";
$header_string .= $query;

$signature_string  = $method . "\n";
$signature_string .= $fqdn . "\n";
$signature_string .= "/" . $api_version . "/" . $path ."\n";
$signature_string .= $header_string;

echo base64_encode(hash_hmac("sha256", $signature_string, $client_key, true));
echo "\n";
?>
```

▼テスト実行コマンド
```
curl -X GET -G \
-H "X-NCMB-Application-Key: アプリケーションキー" \
-H "X-NCMB-Timestamp: 2017-10-17T23:59:24.065Z" \
-H "X-NCMB-Signature: 生成されたシグネチャ" \
-H "Content-Type: application/json"  https://script.mb.api.cloud.nifty.com/2015-09-01/script/foo.js?name=foo
```
## 追加ご案内

なお、過去にPHPでRESTAPIを実行するセミナーを実施しており、当時の説明資料を公開しておりますのでご参考ください。
説明資料URL：https://www.slideshare.net/mobilebackend/3-restapi

この時使用したコードの中でも、以下URLのコード内で、PHPによるシグネチャ生成をしております。
使用したコードURL:https://github.com/ndyuya/ncmb-post-notification/blob/master/ncmb-client.php

`このコード内では、シグネチャ生成する際、109行目でシグネチャ生成用パラメータのソートを行っております。
パラメータを&で連結する際は、自然順序付け・昇順での並び替えが通常必要となりますので、今後ご参考にしていただければ幸いです。`

参考URL：http://mb.cloud.nifty.com/doc/current/rest/common/signature.html#それぞれの値を「&」で連結

一度お試しいただき、またご不明な点がございましたらご連絡頂けますと幸いです。

以上、宜しくお願い致します。

**Comment by nam1c** [comment]
ncmbadmin様
ありがとうございます。
教えていただいた内容で、無事にアクセスできることが確認できました。
これにてクローズとさせていただきます。

**Comment by nam1c** [comment]
@ncmbadmin 

本件issue https://github.com/NIFCLOUD-mbaas/UserCommunity/issues/791

今年(2021)の７月１日以降、上記のサーバスクリプト実行でエラーが発生するようになりました。
status:400
error code:E400001
10.15.0 is invalid version

NCMB管理画面のスクリプトの方で直接実行してもバージョンエラーとなったため
Version 10.15.0
となっていたものを
Version latest
とすることで、管理画面上での直接実行はできるようになりました。

しかし、外部からのREST API呼び出しはversionエラーとなってしまいます。
Version latest に相当するシグネチャの生成とREST API呼び出しについてご教示いただければ幸いです。
