### ISSUE TITLE
Get url parameter and search

### ISSUE THREAD

**Issue by iyener** [NIFTYCloud-mbaas/UserCommunity#799]
一覧ページから詳細ページ開く時URLパラメータ (user_id=3) を使ってｍBaasで検索するのはどうしたらいいでしょうか？

**Comment by goofmint** [comment]
SDKは何になるでしょうか？またはREST APIを直接実行でしょうか？

**Comment by iyener** [comment]
goofmintさん
お返事ありがとうございました。

SDKですが、　ｍBaasのNCMBよ使ってます。
https://github.com/NIFTYCloud-mbaas/MonacaFormApp/blob/master/www/js/app.js　からデモアプリ見ながらやってます。

**Comment by goofmint** [comment]
ということはJavaScript SDKでしょうか？

http://mb.cloud.nifty.com/doc/current/datastore/basic_usage_monaca.html#オブジェクトの取得

この辺りが参考になるかと。
